
/// <reference path="./GObject-2.0.d.ts" />
/// <reference path="./GLib-2.0.d.ts" />

/**
 * Type Definitions for GJS (https://gjs.guide/), generated by [GirGen](https://github.com/aylur/girgen)
 * If you found a bug, create a bug report on [GirGen's Repository](https://github.com/aylur/girgen/issues/new)
 */
declare module "gi://fontconfig?version=2.0" {
    import type GObject from "gi://GObject?version=2.0"
    import type GLib from "gi://GLib?version=2.0"

    


    namespace fontconfig {
        const __name__: "fontconfig"
        const __version: "2.0"
        /**
         */
        abstract class Pattern {
            static readonly $gtype: GObject.GType<Pattern>

            
        }
        /**
         */
        abstract class CharSet {
            static readonly $gtype: GObject.GType<CharSet>

            
        }
        /**
         */
        abstract class Config {
            static readonly $gtype: GObject.GType<Config>

            
        }
        /**
         */
        function init(): void
    }

    export default fontconfig
}