
/// <reference path="./GLib-2.0.d.ts" />
/// <reference path="./GModule-2.0.d.ts" />
/// <reference path="./GObject-2.0.d.ts" />
/// <reference path="./Gio-2.0.d.ts" />
/// <reference path="./Gck-1.d.ts" />
/// <reference path="./freetype2-2.0.d.ts" />
/// <reference path="./HarfBuzz-0.0.d.ts" />
/// <reference path="./cairo-1.0.d.ts" />
/// <reference path="./GdkPixbuf-2.0.d.ts" />
/// <reference path="./Pango-1.0.d.ts" />
/// <reference path="./Atk-1.0.d.ts" />
/// <reference path="./Gdk-3.0.d.ts" />
/// <reference path="./xlib-2.0.d.ts" />
/// <reference path="./Gcr-3.d.ts" />
/// <reference path="./Gtk-3.0.d.ts" />

/**
 * Type Definitions for GJS (https://gjs.guide/), generated by [GirGen](https://github.com/aylur/girgen)
 * If you found a bug, create a bug report on [GirGen's Repository](https://github.com/aylur/girgen/issues/new)
 */
declare module "gi://GcrUi?version=3" {
    import type GLib from "gi://GLib?version=2.0"
    import type GModule from "gi://GModule?version=2.0"
    import type GObject from "gi://GObject?version=2.0"
    import type Gio from "gi://Gio?version=2.0"
    import type Gck from "gi://Gck?version=1"
    import type freetype2 from "gi://freetype2?version=2.0"
    import type HarfBuzz from "gi://HarfBuzz?version=0.0"
    import type cairo from "gi://cairo?version=1.0"
    import type GdkPixbuf from "gi://GdkPixbuf?version=2.0"
    import type Pango from "gi://Pango?version=1.0"
    import type Atk from "gi://Atk?version=1.0"
    import type Gdk from "gi://Gdk?version=3.0"
    import type xlib from "gi://xlib?version=2.0"
    import type Gcr from "gi://Gcr?version=3"
    import type Gtk from "gi://Gtk?version=3.0"

    


    namespace GcrUi {
        const __name__: "GcrUi"
        const __version: "3"
        

        namespace Renderer {
            interface SignalSignatures extends GObject.Object.SignalSignatures {
                /**
                 * A signal that is emitted by the renderer when it's data
                 * changed and should be rerendered.
                 */
                "data-changed"(): void
            }

            interface ReadableProperties extends GObject.Object.ReadableProperties {
                "attributes": Gck.Attributes | null
                "label": string
            }

            interface WritableProperties extends GObject.Object.WritableProperties {
                "attributes": Gck.Attributes | null
                "label": string
            }

            interface ConstructOnlyProperties extends GObject.Object.ConstructOnlyProperties {
            }

            interface Interface extends GObject.Object {
                /**
                 * signal emitted when data being rendered changes
                 */
                vfunc_data_changed(): void
                /**
                 * method invoked to populate a popup menu with additional
                 *                  renderer options
                 * @param viewer
                 * @param menu
                 */
                vfunc_populate_popup(viewer: Viewer, menu: Gtk.Menu): void
                /**
                 * Render the contents of the renderer to the given viewer.
                 * @param viewer The viewer to render to.
                 */
                vfunc_render_view(viewer: Viewer): void
            }
        }

        /**
         * An interface that's implemented by renderers which wish to render data to a
         * [iface@Viewer].
         *
         * The interaction between [iface@Renderer] and [iface@Viewer] is not stable
         * yet, and so new renderers cannot be implemented outside the Gcr library at
         * this time.
         *
         * To lookup a renderer for a given set of attributes, use the gcr_renderer_create()
         * function. This will create and initialize a renderer that's capable of viewing
         * the data in those attributes.
         */
        interface Renderer extends GObject.Object, Renderer.Interface {
            readonly $signals: Renderer.SignalSignatures
            readonly $readableProperties: Renderer.ReadableProperties
            readonly $writableProperties: Renderer.WritableProperties
            readonly $constructOnlyProperties: Renderer.ConstructOnlyProperties
            /**
             * The attributes to display.
             */
            get attributes(): Gck.Attributes | null
            set attributes(value: Gck.Attributes | null)
            /**
             * The label to display.
             */
            get label(): string
            set label(value: string)
            /**
             * Emit the #GcrRenderer::data-changed signal on the renderer. This is used by
             * renderer implementations.
             */
            emit_data_changed(): void
            /**
             * Get the PKCS#11 attributes, if any, set for this renderer to display.
             * @returns the attributes, owned by the renderer
             */
            get_attributes(): Gck.Attributes | null
            /**
             * Called by #GcrViewer when about to display a popup menu for the content
             * displayed by the renderer. The renderer can add a menu item if desired.
             * @param viewer The viewer that is displaying a popup
             * @param menu The popup menu being displayed
             */
            popuplate_popup(viewer: Viewer, menu: Gtk.Menu): void
            /**
             * Render the contents of the renderer to the given viewer.
             * @param viewer The viewer to render to.
             */
            render_view(viewer: Viewer): void
            /**
             * Set the PKCS#11 attributes for this renderer to display.
             * @param attrs attributes to set
             */
            set_attributes(attrs: Gck.Attributes | null): void
        }


        interface RendererIface {
            readonly $gtype: GObject.GType<Renderer>
            readonly prototype: Renderer
            /**
             * Create and initialize a renderer for the given attributes and label. These
             * renderers should have been preregistered via gcr_renderer_register().
             * @param label The label for the renderer
             * @param attrs The attributes to render
             * @returns a new renderer, or %NULL if no renderer          matched the attributes; the render should be released with g_object_unref()
             */
            create(label: string | null, attrs: Gck.Attributes): Renderer | null
            /**
             * Register a renderer to be created when matching attributes are passed to
             * gcr_renderer_create().
             * @param renderer_type The renderer class type
             * @param attrs The attributes to match
             */
            register(renderer_type: (GObject.GType | { $gtype: GObject.GType }), attrs: Gck.Attributes): void
            /**
             * Register all the well known renderers for certificates and keys known to the
             * Gcr library.
             */
            register_well_known(): void

            [Symbol.hasInstance](instance: unknown): instance is Renderer
        }

        const Renderer: RendererIface
        

        namespace Viewer {
            interface SignalSignatures extends Gtk.Widget.SignalSignatures {
            }

            interface ReadableProperties extends Gtk.Widget.ReadableProperties {
            }

            interface WritableProperties extends Gtk.Widget.WritableProperties {
            }

            interface ConstructOnlyProperties extends Gtk.Widget.ConstructOnlyProperties {
            }

            interface Interface extends Gtk.Widget {
                /**
                 * Add a renderer to this viewer.
                 * @param renderer The renderer to add
                 */
                vfunc_add_renderer(renderer: Renderer): void
                /**
                 * Get the number of renderers present in the viewer.
                 * @returns The number of renderers.
                 */
                vfunc_count_renderers(): number
                /**
                 * Get a pointer to the renderer at the given index. It is an error to request
                 * an index that is out of bounds.
                 * @param index_ The index of the renderer to get
                 * @returns the render, owned by the viewer
                 */
                vfunc_get_renderer(index_: number): Renderer
                /**
                 * Insert a renderer at a specific point in the viewer
                 * @param renderer the renderer to insert
                 * @param before the renderer to insert before
                 */
                vfunc_insert_renderer(renderer: Renderer, before: Renderer | null): void
                /**
                 * Remove a renderer from this viewer.
                 * @param renderer The renderer to remove
                 */
                vfunc_remove_renderer(renderer: Renderer): void
            }
        }

        /**
         * An abstract interface that represents a widget that can hold
         * various renderers and display their contents.
         *
         * The interaction between [iface@Renderer] and [iface@Viewer] is not stable
         * yet, and so viewers cannot be implemented outside the Gcr library at this
         * time.
         *
         * Use the [func@Viewer.new] and [func@Viewer.new_scrolled] to get default
         * implementations of viewers.
         */
        interface Viewer extends Gtk.Widget, Viewer.Interface {
            readonly $signals: Viewer.SignalSignatures
            readonly $readableProperties: Viewer.ReadableProperties
            readonly $writableProperties: Viewer.WritableProperties
            readonly $constructOnlyProperties: Viewer.ConstructOnlyProperties
            /**
             * Add a renderer to this viewer.
             * @param renderer The renderer to add
             */
            add_renderer(renderer: Renderer): void
            /**
             * Get the number of renderers present in the viewer.
             * @returns The number of renderers.
             */
            count_renderers(): number
            /**
             * Get a pointer to the renderer at the given index. It is an error to request
             * an index that is out of bounds.
             * @param index_ The index of the renderer to get
             * @returns the render, owned by the viewer
             */
            get_renderer(index_: number): Renderer
            /**
             * Insert a renderer at a specific point in the viewer
             * @param renderer the renderer to insert
             * @param before the renderer to insert before
             */
            insert_renderer(renderer: Renderer, before: Renderer | null): void
            /**
             * Remove a renderer from this viewer.
             * @param renderer The renderer to remove
             */
            remove_renderer(renderer: Renderer): void
        }


        interface ViewerIface {
            readonly $gtype: GObject.GType<Viewer>
            readonly prototype: Viewer
            /**
             * Get an implementation of #GcrViewer that supports a view
             * of multiple renderers.
             * @returns a newly allocated #GcrViewer, which should be          released with g_object_unref()
             */
            "new"(): Viewer
            /**
             * Get an implementation of #GcrViewer that supports a scrolled view
             * of multiple renderers.
             * @returns a #GcrViewer which is also a #GtkWidget
             */
            new_scrolled(): Viewer

            [Symbol.hasInstance](instance: unknown): instance is Viewer
        }

        const Viewer: ViewerIface
        

        namespace CertificateRenderer {
            interface SignalSignatures extends GObject.Object.SignalSignatures, Gcr.Certificate.SignalSignatures, Gcr.Comparable.SignalSignatures, Renderer.SignalSignatures {
            }

            interface ReadableProperties extends GObject.Object.ReadableProperties, Gcr.Certificate.ReadableProperties, Gcr.Comparable.ReadableProperties, Renderer.ReadableProperties {
                "attributes": Gck.Attributes
                "certificate": Gcr.Certificate
                "label": string
            }

            interface WritableProperties extends GObject.Object.WritableProperties, Gcr.Certificate.WritableProperties, Gcr.Comparable.WritableProperties, Renderer.WritableProperties {
                "attributes": Gck.Attributes
                "certificate": Gcr.Certificate
                "label": string
            }

            interface ConstructOnlyProperties extends GObject.Object.ConstructOnlyProperties, Gcr.Certificate.ConstructOnlyProperties, Gcr.Comparable.ConstructOnlyProperties, Renderer.ConstructOnlyProperties {
            }
        }

        /**
         * An implementation of #GcrRenderer which renders certificates.
         */
        interface CertificateRenderer extends GObject.Object, Gcr.Certificate, Gcr.Comparable, Renderer {
            readonly $signals: CertificateRenderer.SignalSignatures
            readonly $readableProperties: CertificateRenderer.ReadableProperties
            readonly $writableProperties: CertificateRenderer.WritableProperties
            readonly $constructOnlyProperties: CertificateRenderer.ConstructOnlyProperties
            /**
             * The certificate attributes to display. One of the attributes must be
             * a CKA_VALUE type attribute which contains a DER encoded certificate.
             */
            get attributes(): Gck.Attributes
            set attributes(value: Gck.Attributes)
            /**
             * The certificate to display. May be %NULL.
             */
            get certificate(): Gcr.Certificate
            set certificate(value: Gcr.Certificate)
            /**
             * The label to display.
             */
            get label(): string
            set label(value: string)
            /**
             * Get the certificate displayed in the renderer. If no certificate was
             * explicitly set, then the renderer will return itself since it acts as
             * a valid certificate.
             * @returns The certificate, owned by the renderer.
             */
            get_certificate(): Gcr.Certificate
            /**
             * Set a certificate to display in the renderer.
             * @param certificate the certificate to display
             */
            set_certificate(certificate: Gcr.Certificate | null): void
        }

        interface CertificateRendererClass extends Omit<GObject.ObjectClass, "new"> {
            readonly $gtype: GObject.GType<CertificateRenderer>
            readonly prototype: CertificateRenderer
            new (props?: Partial<GObject.ConstructorProps<CertificateRenderer>>): CertificateRenderer
            /**
             * Create a new certificate renderer to display the certificate.
             * @param certificate The certificate to display
             * @returns a newly allocated #GcrCertificateRenderer, which          should be released with g_object_unref()
             */
            "new"(certificate: Gcr.Certificate): CertificateRenderer
            /**
             * Create a new certificate renderer to display the label and attributes. One
             * of the attributes should be a CKA_VALUE type attribute containing a DER
             * encoded certificate.
             * @param label the label to display
             * @param attrs The attributes to display
             * @returns a newly allocated #GcrCertificateRenderer, which          should be released with g_object_unref()
             */
            new_for_attributes(label: string | null, attrs: never | null): CertificateRenderer
        }

        const CertificateRenderer: CertificateRendererClass
        

        namespace CertificateWidget {
            interface SignalSignatures extends Gtk.Bin.SignalSignatures, Atk.ImplementorIface.SignalSignatures, Gtk.Buildable.SignalSignatures {
            }

            interface ReadableProperties extends Gtk.Bin.ReadableProperties, Atk.ImplementorIface.ReadableProperties, Gtk.Buildable.ReadableProperties {
                "attributes": Gck.Attributes | null
                "certificate": Gcr.Certificate | null
            }

            interface WritableProperties extends Gtk.Bin.WritableProperties, Atk.ImplementorIface.WritableProperties, Gtk.Buildable.WritableProperties {
                "attributes": Gck.Attributes | null
                "certificate": Gcr.Certificate | null
            }

            interface ConstructOnlyProperties extends Gtk.Bin.ConstructOnlyProperties, Atk.ImplementorIface.ConstructOnlyProperties, Gtk.Buildable.ConstructOnlyProperties {
            }
        }

        /**
         * A widget that can be used to display a certificate.
         *
         * A certificate widget is normally in a collapsed state showing only
         * details, but can be expanded by the user.
         *
         * Use [ctor@CertificateWidget.new] to create a new certificate widget. Only
         * one certificate can be displayed. It contains a [iface@Viewer] internally
         * and [class@CertificateRenderer] is used to render the certificate to the
         * viewer.
         *
         * To show more than one certificate in a view, create the viewer and
         * add renderers to it.
         */
        interface CertificateWidget extends Gtk.Bin, Atk.ImplementorIface, Gtk.Buildable {
            readonly $signals: CertificateWidget.SignalSignatures
            readonly $readableProperties: CertificateWidget.ReadableProperties
            readonly $writableProperties: CertificateWidget.WritableProperties
            readonly $constructOnlyProperties: CertificateWidget.ConstructOnlyProperties
            /**
             */
            get attributes(): Gck.Attributes | null
            set attributes(value: Gck.Attributes | null)
            /**
             */
            get certificate(): Gcr.Certificate | null
            set certificate(value: Gcr.Certificate | null)
            /**
             * Get the attributes displayed in the widget. The attributes should contain
             * a certificate.
             * @returns the attributes, owned by the widget
             */
            get_attributes(): Gck.Attributes | null
            /**
             * Get the certificate displayed in the widget.
             * @returns the certificate
             */
            get_certificate(): Gcr.Certificate | null
            /**
             * Set the attributes displayed in the widget. The attributes should contain
             * a certificate.
             * @param attrs the attributes to display
             */
            set_attributes(attrs: Gck.Attributes | null): void
            /**
             * Set the certificate displayed in the widget
             * @param certificate the certificate to display
             */
            set_certificate(certificate: Gcr.Certificate | null): void
        }

        interface CertificateWidgetClass extends Omit<Gtk.BinClass, "new"> {
            readonly $gtype: GObject.GType<CertificateWidget>
            readonly prototype: CertificateWidget
            new (props?: Partial<GObject.ConstructorProps<CertificateWidget>>): CertificateWidget
            /**
             * Create a new certificate widget which displays a given certificate.
             * @param certificate certificate to display, or %NULL
             * @returns a new certificate widget
             */
            "new"(certificate: Gcr.Certificate | null): CertificateWidget
        }

        const CertificateWidget: CertificateWidgetClass
        

        namespace CollectionModel {
            interface SignalSignatures extends GObject.Object.SignalSignatures, Gtk.TreeModel.SignalSignatures, Gtk.TreeSortable.SignalSignatures {
            }

            interface ReadableProperties extends GObject.Object.ReadableProperties, Gtk.TreeModel.ReadableProperties, Gtk.TreeSortable.ReadableProperties {
                "collection": Gcr.Collection
                "columns": never
            }

            interface WritableProperties extends GObject.Object.WritableProperties, Gtk.TreeModel.WritableProperties, Gtk.TreeSortable.WritableProperties {
                "collection": Gcr.Collection
                "columns": never
            }

            interface ConstructOnlyProperties extends GObject.Object.ConstructOnlyProperties, Gtk.TreeModel.ConstructOnlyProperties, Gtk.TreeSortable.ConstructOnlyProperties {
            }
        }

        /**
         * Ain implementation of a [iface@Gtk.TreeModel] which contains a row for each
         * object in a [iface@Gcr.Collection].
         *
         * As objects are added or removed from the collection, rows are added and
         * removed from this model.
         *
         * The row values come from the properties of the objects in the collection. Use
         * [ctor@CollectionModel.new] to create a new collection model. To have more
         * control over the values use a set of [struct@Gcr.Column] structures to
         * define the columns. This can be done with [ctor@CollectionModel.new_full] or
         * [method@CollectionModel.set_columns].
         *
         * Each row can have a selected state, which is represented by a boolean column.
         * The selected state can be toggled with gcr_collection_model_toggle_selected()
         * or set with gcr_collection_model_set_selected_objects() and retrieved with
         * [method@CollectionModel.get_selected_objects].
         *
         * To determine which object a row represents and vice versa, use the
         * [method@CollectionModel.iter_for_object] or
         * [method@CollectionModel.object_for_iter] functions.
         */
        interface CollectionModel extends GObject.Object, Gtk.TreeModel, Gtk.TreeSortable {
            readonly $signals: CollectionModel.SignalSignatures
            readonly $readableProperties: CollectionModel.ReadableProperties
            readonly $writableProperties: CollectionModel.WritableProperties
            readonly $constructOnlyProperties: CollectionModel.ConstructOnlyProperties
            /**
             */
            get collection(): Gcr.Collection
            set collection(value: Gcr.Collection)
            /**
             */
            get columns(): never
            set columns(value: never)
            /**
             * Set whether a given row is toggled selected or not.
             * @param iter The row
             * @param selected Whether the row should be selected or not.
             */
            change_selected(iter: Gtk.TreeIter, selected: boolean): void
            /**
             * Get the column identifier for the column that contains the values
             * of the selected state.
             * @returns The column identifier.
             */
            column_for_selected(): number
            /**
             * Get the collection which this model represents
             * @returns the collection, owned by the model
             */
            get_collection(): Gcr.Collection
            /**
             * Get a list of checked/selected objects.
             * @returns a list of selected          objects, which should be freed with g_list_free()
             */
            get_selected_objects(): GObject.Object[]
            /**
             * Check whether a given row has been toggled as selected.
             * @param iter The row
             * @returns Whether the row has been selected.
             */
            is_selected(iter: Gtk.TreeIter): boolean
            /**
             * Set @iter to the row for the given object. If the object is not in this
             * model, then %FALSE will be returned.
             * @param object The object
             * @param iter The row for the object
             * @returns %TRUE if the object was present.
             */
            iter_for_object(object: GObject.Object, iter: Gtk.TreeIter): boolean
            /**
             * Get the object that is represented by the given row in the model.
             * @param iter The row
             * @returns The object, owned by the model.
             */
            object_for_iter(iter: Gtk.TreeIter): GObject.Object
            /**
             * Set the collection which this model represents
             * @param collection the collection or %NULL
             */
            set_collection(collection: Gcr.Collection | null): void
            /**
             * Set the checked/selected objects.
             * @param selected a list of objects to select
             */
            set_selected_objects(selected: GObject.Object[]): void
            /**
             * Toggle the selected state of a given row.
             * @param iter The row
             */
            toggle_selected(iter: Gtk.TreeIter): void
        }

        interface CollectionModelClass extends Omit<GObject.ObjectClass, "new"> {
            readonly $gtype: GObject.GType<CollectionModel>
            readonly prototype: CollectionModel
            new (props?: Partial<GObject.ConstructorProps<CollectionModel>>): CollectionModel
        }

        const CollectionModel: CollectionModelClass
        

        namespace ComboSelector {
            interface SignalSignatures extends Gtk.ComboBox.SignalSignatures, Atk.ImplementorIface.SignalSignatures, Gtk.Buildable.SignalSignatures, Gtk.CellEditable.SignalSignatures, Gtk.CellLayout.SignalSignatures {
            }

            interface ReadableProperties extends Gtk.ComboBox.ReadableProperties, Atk.ImplementorIface.ReadableProperties, Gtk.Buildable.ReadableProperties, Gtk.CellEditable.ReadableProperties, Gtk.CellLayout.ReadableProperties {
                "collection": Gcr.Collection
            }

            interface WritableProperties extends Gtk.ComboBox.WritableProperties, Atk.ImplementorIface.WritableProperties, Gtk.Buildable.WritableProperties, Gtk.CellEditable.WritableProperties, Gtk.CellLayout.WritableProperties {
                "collection": Gcr.Collection
            }

            interface ConstructOnlyProperties extends Gtk.ComboBox.ConstructOnlyProperties, Atk.ImplementorIface.ConstructOnlyProperties, Gtk.Buildable.ConstructOnlyProperties, Gtk.CellEditable.ConstructOnlyProperties, Gtk.CellLayout.ConstructOnlyProperties {
            }
        }

        /**
         * A widget that can be used to select a certificate or key. It allows
         * the user to select one object from the selector at a time.
         */
        interface ComboSelector extends Gtk.ComboBox, Atk.ImplementorIface, Gtk.Buildable, Gtk.CellEditable, Gtk.CellLayout {
            readonly $signals: ComboSelector.SignalSignatures
            readonly $readableProperties: ComboSelector.ReadableProperties
            readonly $writableProperties: ComboSelector.WritableProperties
            readonly $constructOnlyProperties: ComboSelector.ConstructOnlyProperties
            /**
             * The collection which contains the objects to display in the selector.
             */
            get collection(): Gcr.Collection
            set collection(value: Gcr.Collection)
            /**
             * Get the collection that this selector is displaying objects from.
             * @returns The collection, owned by the selector.
             */
            get_collection(): Gcr.Collection
            /**
             * Get the selected object in the selector, or %NULL if nothing selected.
             * @returns the selected object, owned by the selector, or %NULL
             */
            get_selected(): GObject.Object
            /**
             * Set the currently selected object in the selector, or clear the selection
             * if selected is set to %NULL.
             * @param selected the object to select or %NULL
             */
            set_selected(selected: GObject.Object | null): void
        }

        interface ComboSelectorClass extends Omit<Gtk.ComboBoxClass, "new"> {
            readonly $gtype: GObject.GType<ComboSelector>
            readonly prototype: ComboSelector
            new (props?: Partial<GObject.ConstructorProps<ComboSelector>>): ComboSelector
            /**
             * Create a new #GcrTreeSelector.
             * @param collection The collection that contains the objects to display
             * @returns A newly allocated selector, which should be released with     g_object_unref().
             */
            "new"(collection: Gcr.Collection): ComboSelector
        }

        const ComboSelector: ComboSelectorClass
        

        namespace FailureRenderer {
            interface SignalSignatures extends GObject.Object.SignalSignatures, Renderer.SignalSignatures {
            }

            interface ReadableProperties extends GObject.Object.ReadableProperties, Renderer.ReadableProperties {
                "attributes": Gck.Attributes
                "label": string
            }

            interface WritableProperties extends GObject.Object.WritableProperties, Renderer.WritableProperties {
                "attributes": Gck.Attributes
                "label": string
            }

            interface ConstructOnlyProperties extends GObject.Object.ConstructOnlyProperties, Renderer.ConstructOnlyProperties {
            }
        }

        /**
         * A renderer that can be used for unsupported data.
         */
        interface FailureRenderer extends GObject.Object, Renderer {
            readonly $signals: FailureRenderer.SignalSignatures
            readonly $readableProperties: FailureRenderer.ReadableProperties
            readonly $writableProperties: FailureRenderer.WritableProperties
            readonly $constructOnlyProperties: FailureRenderer.ConstructOnlyProperties
            /**
             */
            get attributes(): Gck.Attributes
            set attributes(value: Gck.Attributes)
            /**
             */
            get label(): string
            set label(value: string)
        }

        interface FailureRendererClass extends Omit<GObject.ObjectClass, "new"> {
            readonly $gtype: GObject.GType<FailureRenderer>
            readonly prototype: FailureRenderer
            new (props?: Partial<GObject.ConstructorProps<FailureRenderer>>): FailureRenderer
            /**
             * Create a new renderer for an error.
             * @param label the label for the failure
             * @param error the error to display
             * @returns the new renderer
             */
            "new"(label: string | null, error: GLib.Error): FailureRenderer
            /**
             * Create a new renderer for unsupported data.
             * @param label the label for the failure
             * @returns the new renderer
             */
            new_unsupported(label: string): Renderer
        }

        const FailureRenderer: FailureRendererClass
        

        namespace ImportButton {
            interface SignalSignatures extends Gtk.Button.SignalSignatures, Atk.ImplementorIface.SignalSignatures, Gtk.Actionable.SignalSignatures, Gtk.Activatable.SignalSignatures, Gtk.Buildable.SignalSignatures {
                /**
                 * Signal emitted when an import completes or fails.
                 * @param importer the importer that was imported to
                 * @param error if import was successful %NULL, or an error
                 */
                "imported"(importer: GObject.Object, error: GLib.Error): void
                /**
                 * Signal emitted when an import begins.
                 * @param importer the importer that will be imported to
                 */
                "importing"(importer: GObject.Object): void
            }

            interface ReadableProperties extends Gtk.Button.ReadableProperties, Atk.ImplementorIface.ReadableProperties, Gtk.Actionable.ReadableProperties, Gtk.Activatable.ReadableProperties, Gtk.Buildable.ReadableProperties {
            }

            interface WritableProperties extends Gtk.Button.WritableProperties, Atk.ImplementorIface.WritableProperties, Gtk.Actionable.WritableProperties, Gtk.Activatable.WritableProperties, Gtk.Buildable.WritableProperties {
            }

            interface ConstructOnlyProperties extends Gtk.Button.ConstructOnlyProperties, Atk.ImplementorIface.ConstructOnlyProperties, Gtk.Actionable.ConstructOnlyProperties, Gtk.Activatable.ConstructOnlyProperties, Gtk.Buildable.ConstructOnlyProperties {
            }
        }

        /**
         * A button which imports keys and certificates.
         *
         * The import button shows a spinner when the button is activated. When more
         * than one importer is available, it shows a drop down to select which to
         * import to.
         */
        interface ImportButton extends Gtk.Button, Atk.ImplementorIface, Gtk.Actionable, Gtk.Activatable, Gtk.Buildable {
            readonly $signals: ImportButton.SignalSignatures
            readonly $readableProperties: ImportButton.ReadableProperties
            readonly $writableProperties: ImportButton.WritableProperties
            readonly $constructOnlyProperties: ImportButton.ConstructOnlyProperties
            /**
             * Queue an item to import via the button
             * @param parsed a parsed item
             */
            add_parsed(parsed: Gcr.Parsed): void
            /**
             * Emitted when the import completes, or fails.
             * @param importer
             * @param error
             */
            vfunc_imported(importer: Gcr.Importer, error: GLib.Error): void
            /**
             * Emitted when the import begins.
             * @param importer
             */
            vfunc_importing(importer: Gcr.Importer): void
        }

        interface ImportButtonClass extends Omit<Gtk.ButtonClass, "new"> {
            readonly $gtype: GObject.GType<ImportButton>
            readonly prototype: ImportButton
            new (props?: Partial<GObject.ConstructorProps<ImportButton>>): ImportButton
            /**
             * Create a new #GcrImportButton.
             * @param label label to display on the button
             * @returns a newly created #GcrImportButton
             */
            "new"(label: string | null): ImportButton
        }

        const ImportButton: ImportButtonClass
        

        namespace KeyRenderer {
            interface SignalSignatures extends GObject.Object.SignalSignatures, Renderer.SignalSignatures {
            }

            interface ReadableProperties extends GObject.Object.ReadableProperties, Renderer.ReadableProperties {
                "object": Gck.Object
            }

            interface WritableProperties extends GObject.Object.WritableProperties, Renderer.WritableProperties {
                "object": Gck.Object
            }

            interface ConstructOnlyProperties extends GObject.Object.ConstructOnlyProperties, Renderer.ConstructOnlyProperties {
            }
        }

        /**
         * An implementation of #GcrRenderer which renders keys.
         */
        interface KeyRenderer extends GObject.Object, Renderer {
            readonly $signals: KeyRenderer.SignalSignatures
            readonly $readableProperties: KeyRenderer.ReadableProperties
            readonly $writableProperties: KeyRenderer.WritableProperties
            readonly $constructOnlyProperties: KeyRenderer.ConstructOnlyProperties
            /**
             */
            get object(): Gck.Object
            set object(value: Gck.Object)
            /**
             * Get the attributes displayed in the renderer.
             * @returns the attributes, owned by the renderer
             */
            get_attributes(): Gck.Attributes | null
            /**
             * Get the attributes displayed in the renderer. The attributes should represent
             * either an RSA, DSA, or EC key in PKCS#11 style.
             * @param attrs the attributes to display
             */
            set_attributes(attrs: Gck.Attributes | null): void
        }

        interface KeyRendererClass extends Omit<GObject.ObjectClass, "new"> {
            readonly $gtype: GObject.GType<KeyRenderer>
            readonly prototype: KeyRenderer
            new (props?: Partial<GObject.ConstructorProps<KeyRenderer>>): KeyRenderer
            /**
             * Create a new key renderer which renders a given key in the attributes.
             * @param label label describing the key
             * @param attrs key to display, or %NULL
             * @returns a newly allocated #GcrKeyRenderer, which should be          freed with g_object_unref()
             */
            "new"(label: string | null, attrs: Gck.Attributes | null): KeyRenderer
        }

        const KeyRenderer: KeyRendererClass
        

        namespace KeyWidget {
            interface SignalSignatures extends Gtk.Bin.SignalSignatures, Atk.ImplementorIface.SignalSignatures, Gtk.Buildable.SignalSignatures {
            }

            interface ReadableProperties extends Gtk.Bin.ReadableProperties, Atk.ImplementorIface.ReadableProperties, Gtk.Buildable.ReadableProperties {
                "attributes": Gck.Attributes | null
            }

            interface WritableProperties extends Gtk.Bin.WritableProperties, Atk.ImplementorIface.WritableProperties, Gtk.Buildable.WritableProperties {
                "attributes": Gck.Attributes | null
            }

            interface ConstructOnlyProperties extends Gtk.Bin.ConstructOnlyProperties, Atk.ImplementorIface.ConstructOnlyProperties, Gtk.Buildable.ConstructOnlyProperties {
            }
        }

        /**
         * A key widget and renderer
         *
         * A key widget can be used to display a RSA, DSA or EC key. The widget is
         * normally in a collapsed state showing only details, but can be expanded by
         * the user.
         *
         * Use [ctor@KeyWidget.new] to create a new key widget. Only one key can be
         * displayed. A key widget contains a [iface@Viewer] internally and
         * [class@KeyRenderer] is used to render the key to the viewer. To show more
         * than one key in a view, create the viewer and add renderers to it.
         */
        interface KeyWidget extends Gtk.Bin, Atk.ImplementorIface, Gtk.Buildable {
            readonly $signals: KeyWidget.SignalSignatures
            readonly $readableProperties: KeyWidget.ReadableProperties
            readonly $writableProperties: KeyWidget.WritableProperties
            readonly $constructOnlyProperties: KeyWidget.ConstructOnlyProperties
            /**
             */
            get attributes(): Gck.Attributes | null
            set attributes(value: Gck.Attributes | null)
            /**
             * Get the attributes displayed in the widget.
             * @returns The attributes, owned by the widget.
             */
            get_attributes(): Gck.Attributes | null
            /**
             * Get the attributes displayed in the widget. The attributes should represent
             * either an RSA, DSA or EC key in PKCS#11 style.
             * @param attrs the attributes to display
             */
            set_attributes(attrs: Gck.Attributes | null): void
        }

        interface KeyWidgetClass extends Omit<Gtk.BinClass, "new"> {
            readonly $gtype: GObject.GType<KeyWidget>
            readonly prototype: KeyWidget
            new (props?: Partial<GObject.ConstructorProps<KeyWidget>>): KeyWidget
            /**
             * Create a new key widget which displays a given key in the attributes.
             * @param attrs key to display, or %NULL
             * @returns A newly allocated #GcrKeyWidget, which should be freed     with g_object_unref().
             */
            "new"(attrs: Gck.Attributes | null): KeyWidget
        }

        const KeyWidget: KeyWidgetClass
        

        namespace ListSelector {
            interface SignalSignatures extends Gtk.TreeView.SignalSignatures, Atk.ImplementorIface.SignalSignatures, Gtk.Buildable.SignalSignatures, Gtk.Scrollable.SignalSignatures {
            }

            interface ReadableProperties extends Gtk.TreeView.ReadableProperties, Atk.ImplementorIface.ReadableProperties, Gtk.Buildable.ReadableProperties, Gtk.Scrollable.ReadableProperties {
                "collection": Gcr.Collection
            }

            interface WritableProperties extends Gtk.TreeView.WritableProperties, Atk.ImplementorIface.WritableProperties, Gtk.Buildable.WritableProperties, Gtk.Scrollable.WritableProperties {
                "collection": Gcr.Collection
            }

            interface ConstructOnlyProperties extends Gtk.TreeView.ConstructOnlyProperties, Atk.ImplementorIface.ConstructOnlyProperties, Gtk.Buildable.ConstructOnlyProperties, Gtk.Scrollable.ConstructOnlyProperties {
            }
        }

        /**
         * A selector widget to select 1 or more certificates or keys from a list.
         *
         * Live search is available for quick filtering.
         */
        interface ListSelector extends Gtk.TreeView, Atk.ImplementorIface, Gtk.Buildable, Gtk.Scrollable {
            readonly $signals: ListSelector.SignalSignatures
            readonly $readableProperties: ListSelector.ReadableProperties
            readonly $writableProperties: ListSelector.WritableProperties
            readonly $constructOnlyProperties: ListSelector.ConstructOnlyProperties
            /**
             * The collection which contains the objects to display in the selector.
             */
            get collection(): Gcr.Collection
            set collection(value: Gcr.Collection)
            /**
             * Get the collection that this selector is displaying objects from.
             * @returns The collection, owned by the selector.
             */
            get_collection(): Gcr.Collection
            /**
             * Get a list of selected objects.
             * @returns the list of          selected objects, to be released with g_list_free()
             */
            get_selected(): GObject.Object[]
            /**
             * Select certain objects in the selector.
             * @param selected the list of objects to select
             */
            set_selected(selected: GObject.Object[]): void
        }

        interface ListSelectorClass extends Omit<Gtk.TreeViewClass, "new"> {
            readonly $gtype: GObject.GType<ListSelector>
            readonly prototype: ListSelector
            new (props?: Partial<GObject.ConstructorProps<ListSelector>>): ListSelector
            /**
             * Create a new #GcrListSelector.
             * @param collection The collection that contains the objects to display
             * @returns a newly allocated selector, which should be          released with g_object_unref()
             */
            "new"(collection: Gcr.Collection): ListSelector
        }

        const ListSelector: ListSelectorClass
        

        namespace PromptDialog {
            interface SignalSignatures extends Gtk.Dialog.SignalSignatures, Atk.ImplementorIface.SignalSignatures, Gcr.Prompt.SignalSignatures, Gtk.Buildable.SignalSignatures {
            }

            interface ReadableProperties extends Gtk.Dialog.ReadableProperties, Atk.ImplementorIface.ReadableProperties, Gcr.Prompt.ReadableProperties, Gtk.Buildable.ReadableProperties {
                "choice-visible": boolean
                "confirm-visible": boolean
                "password-visible": boolean
                "warning-visible": boolean
            }

            interface WritableProperties extends Gtk.Dialog.WritableProperties, Atk.ImplementorIface.WritableProperties, Gcr.Prompt.WritableProperties, Gtk.Buildable.WritableProperties {
                "choice-visible": boolean
                "confirm-visible": boolean
                "password-visible": boolean
                "warning-visible": boolean
            }

            interface ConstructOnlyProperties extends Gtk.Dialog.ConstructOnlyProperties, Atk.ImplementorIface.ConstructOnlyProperties, Gcr.Prompt.ConstructOnlyProperties, Gtk.Buildable.ConstructOnlyProperties {
            }
        }

        /**
         * A [iface@Gcr.Prompt] implementation which shows a GTK dialog. The dialog
         * will remain visible (but insensitive) between prompts. If the user cancels
         * the dialog between prompts, then the dialog will be hidden.
         */
        interface PromptDialog extends Gtk.Dialog, Atk.ImplementorIface, Gcr.Prompt, Gtk.Buildable {
            readonly $signals: PromptDialog.SignalSignatures
            readonly $readableProperties: PromptDialog.ReadableProperties
            readonly $writableProperties: PromptDialog.WritableProperties
            readonly $constructOnlyProperties: PromptDialog.ConstructOnlyProperties
            /**
             * Whether the choice check box is visible or not.
             * @default FALSE
             */
            get choiceVisible(): boolean
            set choiceVisible(value: boolean)
            /**
             * Whether the password confirm entry is visible or not.
             * @default FALSE
             */
            get confirmVisible(): boolean
            set confirmVisible(value: boolean)
            /**
             * Whether the password entry is visible or not.
             * @default FALSE
             */
            get passwordVisible(): boolean
            set passwordVisible(value: boolean)
            /**
             * Whether the warning label is visible or not.
             * @default FALSE
             */
            get warningVisible(): boolean
            set warningVisible(value: boolean)
        }

        interface PromptDialogClass extends Omit<Gtk.DialogClass, "new"> {
            readonly $gtype: GObject.GType<PromptDialog>
            readonly prototype: PromptDialog
            new (props?: Partial<GObject.ConstructorProps<PromptDialog>>): PromptDialog
        }

        const PromptDialog: PromptDialogClass
        

        namespace SecureEntryBuffer {
            interface SignalSignatures extends Gtk.EntryBuffer.SignalSignatures {
            }

            interface ReadableProperties extends Gtk.EntryBuffer.ReadableProperties {
            }

            interface WritableProperties extends Gtk.EntryBuffer.WritableProperties {
            }

            interface ConstructOnlyProperties extends Gtk.EntryBuffer.ConstructOnlyProperties {
            }
        }

        /**
         * A [class@Gtk.EntryBuffer] that uses non-pageable memory.
         *
         * It's good practice to try to keep passwords or sensitive secrets out of
         * pageable memory whenever possible, so that they don't get written to disk.
         *
         * A [class@SecureEntryBuffer] is a [class@Gtk.EntryBuffer] to be used with
         * [class@Gtk.Entry] which uses non-pageable memory to store a password placed
         * in the entry. In order to make any sense at all, the entry must have it's
         * visibility turned off, and just be displaying place holder characters for
         * the text. That is, a password style entry.
         *
         * Use [ctor@Gtk.Entry.new_with_buffer] or [method@Gtk.Entry.set_buffer] to set this buffer
         * on an entry.
         */
        interface SecureEntryBuffer extends Gtk.EntryBuffer {
            readonly $signals: SecureEntryBuffer.SignalSignatures
            readonly $readableProperties: SecureEntryBuffer.ReadableProperties
            readonly $writableProperties: SecureEntryBuffer.WritableProperties
            readonly $constructOnlyProperties: SecureEntryBuffer.ConstructOnlyProperties
        }

        interface SecureEntryBufferClass extends Omit<Gtk.EntryBufferClass, "new"> {
            readonly $gtype: GObject.GType<SecureEntryBuffer>
            readonly prototype: SecureEntryBuffer
            new (props?: Partial<GObject.ConstructorProps<SecureEntryBuffer>>): SecureEntryBuffer
            /**
             * Create a new secure entry buffer.
             * @returns the new entry buffer
             */
            "new"(): SecureEntryBuffer
        }

        const SecureEntryBuffer: SecureEntryBufferClass
        

        namespace TreeSelector {
            interface SignalSignatures extends Gtk.TreeView.SignalSignatures, Atk.ImplementorIface.SignalSignatures, Gtk.Buildable.SignalSignatures, Gtk.Scrollable.SignalSignatures {
            }

            interface ReadableProperties extends Gtk.TreeView.ReadableProperties, Atk.ImplementorIface.ReadableProperties, Gtk.Buildable.ReadableProperties, Gtk.Scrollable.ReadableProperties {
                "collection": Gcr.Collection
                "columns": never
            }

            interface WritableProperties extends Gtk.TreeView.WritableProperties, Atk.ImplementorIface.WritableProperties, Gtk.Buildable.WritableProperties, Gtk.Scrollable.WritableProperties {
                "collection": Gcr.Collection
                "columns": never
            }

            interface ConstructOnlyProperties extends Gtk.TreeView.ConstructOnlyProperties, Atk.ImplementorIface.ConstructOnlyProperties, Gtk.Buildable.ConstructOnlyProperties, Gtk.Scrollable.ConstructOnlyProperties {
            }
        }

        /**
         * A tree selector can be used to select certificates or keys. It allows
         * the user to select multiple objects from a tree.
         */
        interface TreeSelector extends Gtk.TreeView, Atk.ImplementorIface, Gtk.Buildable, Gtk.Scrollable {
            readonly $signals: TreeSelector.SignalSignatures
            readonly $readableProperties: TreeSelector.ReadableProperties
            readonly $writableProperties: TreeSelector.WritableProperties
            readonly $constructOnlyProperties: TreeSelector.ConstructOnlyProperties
            /**
             * The collection which contains the objects to display in the selector.
             */
            get collection(): Gcr.Collection
            set collection(value: Gcr.Collection)
            /**
             * The columns to use to display the objects.
             */
            get columns(): never
            set columns(value: never)
            /**
             * Get the collection that this selector is displaying objects from.
             * @returns the collection, owned by the selector
             */
            get_collection(): Gcr.Collection
            /**
             * Get a list of selected objects.
             * @returns the list of selected          objects, to be released with g_list_free()
             */
            get_selected(): GObject.Object[]
            /**
             * Select certain objects in the selector.
             * @param selected the list of objects to select
             */
            set_selected(selected: GObject.Object[]): void
        }

        interface TreeSelectorClass extends Omit<Gtk.TreeViewClass, "new"> {
            readonly $gtype: GObject.GType<TreeSelector>
            readonly prototype: TreeSelector
            new (props?: Partial<GObject.ConstructorProps<TreeSelector>>): TreeSelector
        }

        const TreeSelector: TreeSelectorClass
        

        namespace UnlockOptionsWidget {
            interface SignalSignatures extends Gtk.Bin.SignalSignatures, Atk.ImplementorIface.SignalSignatures, Gtk.Buildable.SignalSignatures {
            }

            interface ReadableProperties extends Gtk.Bin.ReadableProperties, Atk.ImplementorIface.ReadableProperties, Gtk.Buildable.ReadableProperties {
                "choice": string
                "ttl": number
            }

            interface WritableProperties extends Gtk.Bin.WritableProperties, Atk.ImplementorIface.WritableProperties, Gtk.Buildable.WritableProperties {
                "choice": string
                "ttl": number
            }

            interface ConstructOnlyProperties extends Gtk.Bin.ConstructOnlyProperties, Atk.ImplementorIface.ConstructOnlyProperties, Gtk.Buildable.ConstructOnlyProperties {
            }
        }

        /**
         * This widget displays a set of unlock options for the user to select.
         *
         * The user can choose between keeping caching the unlock indefinitely, or for
         * a given amount of time.
         *
         * Each option has a different name, for example #GCR_UNLOCK_OPTION_ALWAYS. These
         * names are used together with the various functions like
         * [method@UnlockOptionsWidget.get_choice].
         */
        interface UnlockOptionsWidget extends Gtk.Bin, Atk.ImplementorIface, Gtk.Buildable {
            readonly $signals: UnlockOptionsWidget.SignalSignatures
            readonly $readableProperties: UnlockOptionsWidget.ReadableProperties
            readonly $writableProperties: UnlockOptionsWidget.WritableProperties
            readonly $constructOnlyProperties: UnlockOptionsWidget.ConstructOnlyProperties
            /**
             * @default NULL
             */
            get choice(): string
            set choice(value: string)
            /**
             * @default 0
             */
            get ttl(): number
            set ttl(value: number)
            /**
             * Get the currently selected option, like %GCR_UNLOCK_OPTION_ALWAYS.
             * @returns The currently selected option name.
             */
            get_choice(): string
            /**
             * Get the label for one of the options. Use an option name like
             * %GCR_UNLOCK_OPTION_ALWAYS.
             * @param option The option name
             * @returns The current label for the option.
             */
            get_label(option: string): string
            /**
             * Get the sensitivity state for one of the options. Use an option name like
             * %GCR_UNLOCK_OPTION_ALWAYS.
             * @param option The option name
             * @returns Whether the option is sensitive or not.
             */
            get_sensitive(option: string): boolean
            /**
             * Get the timeout setting set for unlock options that have a timeout.
             * This will also return a valid value if the currently selected option
             * does not have a timeout.
             * @returns The unlock timeout in seconds.
             */
            get_ttl(): number
            /**
             * Set the currently selected option. Use an option name like
             * %GCR_UNLOCK_OPTION_ALWAYS.
             * @param option The option name
             */
            set_choice(option: string): void
            /**
             * Set the label for one of the options. Use an option name like
             * %GCR_UNLOCK_OPTION_ALWAYS.
             * @param option The option name
             * @param text The new label
             */
            set_label(option: string, text: string): void
            /**
             * Set the sensitivity state for one of the options. Use an option name like
             * %GCR_UNLOCK_OPTION_ALWAYS. The reason will be displayed as a tooltip.
             * @param option The option name
             * @param sensitive The sensitivity state.
             * @param reason A user displayable string which contains the reason for the sensitivity.
             */
            set_sensitive(option: string, sensitive: boolean, reason: string): void
            /**
             * Set the current setting for the timeout. This can be set even when the
             * currently selected option does not have a timeout.
             * @param ttl The timeout to set, in seconds
             */
            set_ttl(ttl: number): void
        }

        interface UnlockOptionsWidgetClass extends Omit<Gtk.BinClass, "new"> {
            readonly $gtype: GObject.GType<UnlockOptionsWidget>
            readonly prototype: UnlockOptionsWidget
            new (props?: Partial<GObject.ConstructorProps<UnlockOptionsWidget>>): UnlockOptionsWidget
            /**
             * Create a new #GcrUnlockOptionsWidget.
             * @returns a new #GcrUnlockOptionsWidget
             */
            "new"(): UnlockOptionsWidget
        }

        const UnlockOptionsWidget: UnlockOptionsWidgetClass
        

        namespace ViewerWidget {
            interface SignalSignatures extends Gtk.Box.SignalSignatures, Atk.ImplementorIface.SignalSignatures, Gtk.Buildable.SignalSignatures, Gtk.Orientable.SignalSignatures {
                /**
                 * This signal is emitted when an item is added to the viewer widget.
                 * @param renderer the renderer that was added
                 * @param parsed the parsed item that was added
                 */
                "added"(renderer: Renderer, parsed: Gcr.Parsed): void
            }

            interface ReadableProperties extends Gtk.Box.ReadableProperties, Atk.ImplementorIface.ReadableProperties, Gtk.Buildable.ReadableProperties, Gtk.Orientable.ReadableProperties {
                "display-name": string
                "parser": Gcr.Parser
            }

            interface WritableProperties extends Gtk.Box.WritableProperties, Atk.ImplementorIface.WritableProperties, Gtk.Buildable.WritableProperties, Gtk.Orientable.WritableProperties {
                "display-name": string
                "parser": Gcr.Parser
            }

            interface ConstructOnlyProperties extends Gtk.Box.ConstructOnlyProperties, Atk.ImplementorIface.ConstructOnlyProperties, Gtk.Buildable.ConstructOnlyProperties, Gtk.Orientable.ConstructOnlyProperties {
            }
        }

        /**
         * A viewer widget which can display certificates and keys that are
         * located in files.
         */
        interface ViewerWidget extends Gtk.Box, Atk.ImplementorIface, Gtk.Buildable, Gtk.Orientable {
            readonly $signals: ViewerWidget.SignalSignatures
            readonly $readableProperties: ViewerWidget.ReadableProperties
            readonly $writableProperties: ViewerWidget.WritableProperties
            readonly $constructOnlyProperties: ViewerWidget.ConstructOnlyProperties
            /**
             * Display name for data being displayed. This is automatically
             * calculated from a loaded file, or can be explicitly set.
             *
             * Used as a hint when displaying a title for the data, but may be
             * overridden by the parsed data.
             * @default NULL
             */
            get displayName(): string
            set displayName(value: string)
            /**
             * The parser used to parse loaded data into viewable items.
             */
            get parser(): Gcr.Parser
            set parser(value: Gcr.Parser)
            /**
             * Clear the error displayed on the viewer widget.
             */
            clear_error(): void
            /**
             * Get the display name for data being displayed. This is automatically
             * calculated from a loaded file, or can be explicitly set.
             *
             * Used as a hint when displaying a title for the data, but may be
             * overridden by the parsed data.
             * @returns the display name
             */
            get_display_name(): string
            /**
             * Get the parser used to parse loaded data into viewable items.
             * @returns the parser
             */
            get_parser(): Gcr.Parser
            /**
             * Get the viewer used to display the viewable items.
             * @returns the viewer
             */
            get_viewer(): Viewer
            /**
             * Parse and load some data to be displayed into the viewer widgets. The data
             * may contain multiple parseable items if the format can contain multiple
             * items.
             * @param display_name label for the loaded data
             * @param data data to load
             */
            load_bytes(display_name: string | null, data: GLib.Bytes): void
            /**
             * Parse and load some data to be displayed into the viewer widgets. The data
             * may contain multiple parseable items if the format can contain multiple
             * items.
             *
             * This function will copy the data. Use [method@ViewerWidget.load_bytes] to avoid
             * copying the data.
             * @param display_name label for the loaded data
             * @param data data to load
             */
            load_data(display_name: string | null, data: Uint8Array): void
            /**
             * Display contents of a file in the viewer widget. Multiple files can
             * be loaded.
             * @param file a file to load
             */
            load_file(file: Gio.File): void
            /**
             * Set the display name for data being displayed. Once explicitly
             * set it will no longer be calculated automatically by loading data.
             *
             * Used as a hint when displaying a title for the data, but may be
             * overridden by the parsed data.
             * @param display_name the display name
             */
            set_display_name(display_name: string): void
            /**
             * Show an error on the viewer widget. This is displayed on a info bar near
             * the edge of the widget.
             * @param message descriptive error message
             * @param error detailed error
             */
            show_error(message: string, error: GLib.Error | null): void
        }

        interface ViewerWidgetClass extends Omit<Gtk.BoxClass, "new"> {
            readonly $gtype: GObject.GType<ViewerWidget>
            readonly prototype: ViewerWidget
            new (props?: Partial<GObject.ConstructorProps<ViewerWidget>>): ViewerWidget
            /**
             * Create a new viewer widget.
             * @returns A new #GcrViewerWidget object
             */
            "new"(): ViewerWidget
        }

        const ViewerWidget: ViewerWidgetClass
        none
        /**
         */
        abstract class CertificateRendererPrivate {
            static readonly $gtype: GObject.GType<CertificateRendererPrivate>

            
        }
        none
        /**
         */
        abstract class CertificateWidgetPrivate {
            static readonly $gtype: GObject.GType<CertificateWidgetPrivate>

            
        }
        none
        /**
         */
        abstract class CollectionModelPrivate {
            static readonly $gtype: GObject.GType<CollectionModelPrivate>

            
        }
        none
        /**
         */
        abstract class ComboSelectorPrivate {
            static readonly $gtype: GObject.GType<ComboSelectorPrivate>

            
        }
        none
        /**
         */
        abstract class FailureRendererPrivate {
            static readonly $gtype: GObject.GType<FailureRendererPrivate>

            
        }
        none
        /**
         */
        abstract class ImportButtonPrivate {
            static readonly $gtype: GObject.GType<ImportButtonPrivate>

            
        }
        none
        /**
         */
        abstract class KeyRendererPrivate {
            static readonly $gtype: GObject.GType<KeyRendererPrivate>

            
        }
        none
        /**
         */
        abstract class KeyWidgetPrivate {
            static readonly $gtype: GObject.GType<KeyWidgetPrivate>

            
        }
        none
        /**
         */
        abstract class ListSelectorPrivate {
            static readonly $gtype: GObject.GType<ListSelectorPrivate>

            
        }
        none
        /**
         */
        abstract class PromptDialogPrivate {
            static readonly $gtype: GObject.GType<PromptDialogPrivate>

            
        }
        none
        none
        /**
         */
        abstract class SecureEntryBufferPrivate {
            static readonly $gtype: GObject.GType<SecureEntryBufferPrivate>

            
        }
        none
        /**
         */
        abstract class TreeSelectorPrivate {
            static readonly $gtype: GObject.GType<TreeSelectorPrivate>

            
        }
        none
        /**
         */
        abstract class UnlockOptionsWidgetPrivate {
            static readonly $gtype: GObject.GType<UnlockOptionsWidgetPrivate>

            
        }
        none
        none
        /**
         * Create and initialize a renderer for the given attributes and label. These
         * renderers should have been preregistered via gcr_renderer_register().
         * @param label The label for the renderer
         * @param attrs The attributes to render
         * @returns a new renderer, or %NULL if no renderer          matched the attributes; the render should be released with g_object_unref()
         */
        function renderer_create(label: string | null, attrs: Gck.Attributes): Renderer | null
        /**
         * Register a renderer to be created when matching attributes are passed to
         * gcr_renderer_create().
         * @param renderer_type The renderer class type
         * @param attrs The attributes to match
         */
        function renderer_register(renderer_type: (GObject.GType | { $gtype: GObject.GType }), attrs: Gck.Attributes): void
        /**
         * Register all the well known renderers for certificates and keys known to the
         * Gcr library.
         */
        function renderer_register_well_known(): void
        /**
         * Get an implementation of #GcrViewer that supports a view
         * of multiple renderers.
         * @returns a newly allocated #GcrViewer, which should be          released with g_object_unref()
         */
        function viewer_new(): Viewer
        /**
         * Get an implementation of #GcrViewer that supports a scrolled view
         * of multiple renderers.
         * @returns a #GcrViewer which is also a #GtkWidget
         */
        function viewer_new_scrolled(): Viewer
        
        namespace CollectionModelMode {
            const $gtype: GObject.GType<CollectionModelMode>
        }

        /**
         * If a [class@CollectionModel] is created with a mode of
         * %GCR_COLLECTION_MODEL_TREE, then any included objects that are themselves a
         * [iface@Gcr.Collection], will have all child
         * objects include as child rows in a tree form.
         */
        enum CollectionModelMode {
            /**
             * only objects in the top collection, no child objects
             */
            "LIST" = 0,
            /**
             * show objects in the collection, and child objects in a tree form
             */
            "TREE" = 1,
        }
    }

    export default GcrUi
}