
/// <reference path="./GObject-2.0.d.ts" />
/// <reference path="./GLib-2.0.d.ts" />

/**
 * Type Definitions for GJS (https://gjs.guide/), generated by [GirGen](https://github.com/aylur/girgen)
 * If you found a bug, create a bug report on [GirGen's Repository](https://github.com/aylur/girgen/issues/new)
 */
declare module "gi://GDesktopEnums?version=3.0" {
    import type GObject from "gi://GObject?version=2.0"
    import type GLib from "gi://GLib?version=2.0"

    


    namespace GDesktopEnums {
        const __name__: "GDesktopEnums"
        const __version: "3.0"
        
        namespace AccentColor {
            const $gtype: GObject.GType<AccentColor>
        }

        /**
         */
        enum AccentColor {
            /**
             */
            "BLUE" = 0,
            /**
             */
            "TEAL" = 1,
            /**
             */
            "GREEN" = 2,
            /**
             */
            "YELLOW" = 3,
            /**
             */
            "ORANGE" = 4,
            /**
             */
            "RED" = 5,
            /**
             */
            "PINK" = 6,
            /**
             */
            "PURPLE" = 7,
            /**
             */
            "SLATE" = 8,
        }
        
        namespace BackgroundShading {
            const $gtype: GObject.GType<BackgroundShading>
        }

        /**
         */
        enum BackgroundShading {
            /**
             */
            "SOLID" = 0,
            /**
             */
            "VERTICAL" = 1,
            /**
             */
            "HORIZONTAL" = 2,
        }
        
        namespace BackgroundStyle {
            const $gtype: GObject.GType<BackgroundStyle>
        }

        /**
         */
        enum BackgroundStyle {
            /**
             */
            "NONE" = 0,
            /**
             */
            "WALLPAPER" = 1,
            /**
             */
            "CENTERED" = 2,
            /**
             */
            "SCALED" = 3,
            /**
             */
            "STRETCHED" = 4,
            /**
             */
            "ZOOM" = 5,
            /**
             */
            "SPANNED" = 6,
        }
        
        namespace ClockFormat {
            const $gtype: GObject.GType<ClockFormat>
        }

        /**
         */
        enum ClockFormat {
            /**
             */
            "24H" = 0,
            /**
             */
            "12H" = 1,
        }
        
        namespace ColorScheme {
            const $gtype: GObject.GType<ColorScheme>
        }

        /**
         */
        enum ColorScheme {
            /**
             */
            "DEFAULT" = 0,
            /**
             */
            "PREFER_DARK" = 1,
            /**
             */
            "PREFER_LIGHT" = 2,
        }
        
        namespace DeviceSendEvents {
            const $gtype: GObject.GType<DeviceSendEvents>
        }

        /**
         */
        enum DeviceSendEvents {
            /**
             */
            "ENABLED" = 0,
            /**
             */
            "DISABLED" = 1,
            /**
             */
            "DISABLED_ON_EXTERNAL_MOUSE" = 2,
        }
        
        namespace FocusMode {
            const $gtype: GObject.GType<FocusMode>
        }

        /**
         */
        enum FocusMode {
            /**
             */
            "CLICK" = 0,
            /**
             */
            "SLOPPY" = 1,
            /**
             */
            "MOUSE" = 2,
        }
        
        namespace FocusNewWindows {
            const $gtype: GObject.GType<FocusNewWindows>
        }

        /**
         */
        enum FocusNewWindows {
            /**
             */
            "SMART" = 0,
            /**
             */
            "STRICT" = 1,
        }
        
        namespace FontAntialiasingMode {
            const $gtype: GObject.GType<FontAntialiasingMode>
        }

        /**
         */
        enum FontAntialiasingMode {
            /**
             */
            "NONE" = 0,
            /**
             */
            "GRAYSCALE" = 1,
            /**
             */
            "RGBA" = 2,
        }
        
        namespace FontHinting {
            const $gtype: GObject.GType<FontHinting>
        }

        /**
         */
        enum FontHinting {
            /**
             */
            "NONE" = 0,
            /**
             */
            "SLIGHT" = 1,
            /**
             */
            "MEDIUM" = 2,
            /**
             */
            "FULL" = 3,
        }
        
        namespace FontRendering {
            const $gtype: GObject.GType<FontRendering>
        }

        /**
         */
        enum FontRendering {
            /**
             */
            "AUTOMATIC" = 0,
            /**
             */
            "MANUAL" = 1,
        }
        
        namespace FontRgbaOrder {
            const $gtype: GObject.GType<FontRgbaOrder>
        }

        /**
         */
        enum FontRgbaOrder {
            /**
             */
            "RGBA" = 0,
            /**
             */
            "RGB" = 1,
            /**
             */
            "BGR" = 2,
            /**
             */
            "VRGB" = 3,
            /**
             */
            "VBGR" = 4,
        }
        
        namespace LocationAccuracyLevel {
            const $gtype: GObject.GType<LocationAccuracyLevel>
        }

        /**
         */
        enum LocationAccuracyLevel {
            /**
             */
            "COUNTRY" = 0,
            /**
             */
            "CITY" = 1,
            /**
             */
            "NEIGHBORHOOD" = 2,
            /**
             */
            "STREET" = 3,
            /**
             */
            "EXACT" = 4,
        }
        
        namespace MagnifierCaretTrackingMode {
            const $gtype: GObject.GType<MagnifierCaretTrackingMode>
        }

        /**
         */
        enum MagnifierCaretTrackingMode {
            /**
             */
            "NONE" = 0,
            /**
             */
            "CENTERED" = 1,
            /**
             */
            "PROPORTIONAL" = 2,
            /**
             */
            "PUSH" = 3,
        }
        
        namespace MagnifierFocusTrackingMode {
            const $gtype: GObject.GType<MagnifierFocusTrackingMode>
        }

        /**
         */
        enum MagnifierFocusTrackingMode {
            /**
             */
            "NONE" = 0,
            /**
             */
            "CENTERED" = 1,
            /**
             */
            "PROPORTIONAL" = 2,
            /**
             */
            "PUSH" = 3,
        }
        
        namespace MagnifierMouseTrackingMode {
            const $gtype: GObject.GType<MagnifierMouseTrackingMode>
        }

        /**
         */
        enum MagnifierMouseTrackingMode {
            /**
             */
            "NONE" = 0,
            /**
             */
            "CENTERED" = 1,
            /**
             */
            "PROPORTIONAL" = 2,
            /**
             */
            "PUSH" = 3,
        }
        
        namespace MagnifierScreenPosition {
            const $gtype: GObject.GType<MagnifierScreenPosition>
        }

        /**
         */
        enum MagnifierScreenPosition {
            /**
             */
            "NONE" = 0,
            /**
             */
            "FULL_SCREEN" = 1,
            /**
             */
            "TOP_HALF" = 2,
            /**
             */
            "BOTTOM_HALF" = 3,
            /**
             */
            "LEFT_HALF" = 4,
            /**
             */
            "RIGHT_HALF" = 5,
        }
        
        namespace MouseDwellDirection {
            const $gtype: GObject.GType<MouseDwellDirection>
        }

        /**
         */
        enum MouseDwellDirection {
            /**
             */
            "LEFT" = 0,
            /**
             */
            "RIGHT" = 1,
            /**
             */
            "UP" = 2,
            /**
             */
            "DOWN" = 3,
        }
        
        namespace MouseDwellMode {
            const $gtype: GObject.GType<MouseDwellMode>
        }

        /**
         */
        enum MouseDwellMode {
            /**
             */
            "WINDOW" = 0,
            /**
             */
            "GESTURE" = 1,
        }
        
        namespace PadButtonAction {
            const $gtype: GObject.GType<PadButtonAction>
        }

        /**
         */
        enum PadButtonAction {
            /**
             */
            "NONE" = 0,
            /**
             */
            "HELP" = 1,
            /**
             */
            "SWITCH_MONITOR" = 2,
            /**
             */
            "KEYBINDING" = 3,
        }
        
        namespace PointerAccelProfile {
            const $gtype: GObject.GType<PointerAccelProfile>
        }

        /**
         */
        enum PointerAccelProfile {
            /**
             */
            "DEFAULT" = 0,
            /**
             */
            "FLAT" = 1,
            /**
             */
            "ADAPTIVE" = 2,
        }
        
        namespace PointingStickScrollMethod {
            const $gtype: GObject.GType<PointingStickScrollMethod>
        }

        /**
         */
        enum PointingStickScrollMethod {
            /**
             */
            "DEFAULT" = 0,
            /**
             */
            "NONE" = 1,
            /**
             */
            "ON_BUTTON_DOWN" = 2,
        }
        
        namespace ProxyMode {
            const $gtype: GObject.GType<ProxyMode>
        }

        /**
         */
        enum ProxyMode {
            /**
             */
            "NONE" = 0,
            /**
             */
            "MANUAL" = 1,
            /**
             */
            "AUTO" = 2,
        }
        
        namespace ReducedMotion {
            const $gtype: GObject.GType<ReducedMotion>
        }

        /**
         */
        enum ReducedMotion {
            /**
             */
            "NO_PREFERENCE" = 0,
            /**
             */
            "REDUCE" = 1,
        }
        
        namespace ScreensaverMode {
            const $gtype: GObject.GType<ScreensaverMode>
        }

        /**
         */
        enum ScreensaverMode {
            /**
             */
            "BLANK_ONLY" = 0,
            /**
             */
            "RANDOM" = 1,
            /**
             */
            "SINGLE" = 2,
        }
        
        namespace StylusButtonAction {
            const $gtype: GObject.GType<StylusButtonAction>
        }

        /**
         */
        enum StylusButtonAction {
            /**
             */
            "DEFAULT" = 0,
            /**
             */
            "MIDDLE" = 1,
            /**
             */
            "RIGHT" = 2,
            /**
             */
            "BACK" = 3,
            /**
             */
            "FORWARD" = 4,
            /**
             */
            "SWITCH_MONITOR" = 5,
            /**
             */
            "KEYBINDING" = 6,
        }
        
        namespace StylusEraserButtonMode {
            const $gtype: GObject.GType<StylusEraserButtonMode>
        }

        /**
         */
        enum StylusEraserButtonMode {
            /**
             */
            "DEFAULT" = 0,
            /**
             */
            "BUTTON" = 1,
        }
        
        namespace TabletMapping {
            const $gtype: GObject.GType<TabletMapping>
        }

        /**
         */
        enum TabletMapping {
            /**
             */
            "ABSOLUTE" = 0,
            /**
             */
            "RELATIVE" = 1,
        }
        
        namespace TitlebarAction {
            const $gtype: GObject.GType<TitlebarAction>
        }

        /**
         */
        enum TitlebarAction {
            /**
             */
            "TOGGLE_SHADE" = 0,
            /**
             */
            "TOGGLE_MAXIMIZE" = 1,
            /**
             */
            "TOGGLE_MAXIMIZE_HORIZONTALLY" = 2,
            /**
             */
            "TOGGLE_MAXIMIZE_VERTICALLY" = 3,
            /**
             */
            "MINIMIZE" = 4,
            /**
             */
            "NONE" = 5,
            /**
             */
            "LOWER" = 6,
            /**
             */
            "MENU" = 7,
        }
        
        namespace ToolbarIconSize {
            const $gtype: GObject.GType<ToolbarIconSize>
        }

        /**
         */
        enum ToolbarIconSize {
            /**
             */
            "SMALL" = 0,
            /**
             */
            "LARGE" = 1,
        }
        
        namespace ToolbarStyle {
            const $gtype: GObject.GType<ToolbarStyle>
        }

        /**
         */
        enum ToolbarStyle {
            /**
             */
            "BOTH" = 0,
            /**
             */
            "BOTH_HORIZ" = 1,
            /**
             */
            "ICONS" = 2,
            /**
             */
            "TEXT" = 3,
        }
        
        namespace TouchpadClickMethod {
            const $gtype: GObject.GType<TouchpadClickMethod>
        }

        /**
         */
        enum TouchpadClickMethod {
            /**
             */
            "DEFAULT" = 0,
            /**
             */
            "NONE" = 1,
            /**
             */
            "AREAS" = 2,
            /**
             */
            "FINGERS" = 3,
        }
        
        namespace TouchpadHandedness {
            const $gtype: GObject.GType<TouchpadHandedness>
        }

        /**
         */
        enum TouchpadHandedness {
            /**
             */
            "RIGHT" = 0,
            /**
             */
            "LEFT" = 1,
            /**
             */
            "MOUSE" = 2,
        }
        
        namespace TouchpadTapButtonMap {
            const $gtype: GObject.GType<TouchpadTapButtonMap>
        }

        /**
         */
        enum TouchpadTapButtonMap {
            /**
             */
            "DEFAULT" = 0,
            /**
             */
            "LRM" = 1,
            /**
             */
            "LMR" = 2,
        }
        
        namespace UsbProtection {
            const $gtype: GObject.GType<UsbProtection>
        }

        /**
         */
        enum UsbProtection {
            /**
             */
            "LOCKSCREEN" = 0,
            /**
             */
            "ALWAYS" = 1,
        }
        
        namespace VisualBellType {
            const $gtype: GObject.GType<VisualBellType>
        }

        /**
         */
        enum VisualBellType {
            /**
             */
            "FULLSCREEN_FLASH" = 0,
            /**
             */
            "FRAME_FLASH" = 1,
        }
        
        namespace Weekday {
            const $gtype: GObject.GType<Weekday>
        }

        /**
         */
        enum Weekday {
            /**
             */
            "DEFAULT" = 0,
            /**
             */
            "MONDAY" = 1,
            /**
             */
            "TUESDAY" = 2,
            /**
             */
            "WEDNESDAY" = 3,
            /**
             */
            "THURSDAY" = 4,
            /**
             */
            "FRIDAY" = 5,
            /**
             */
            "SATURDAY" = 6,
            /**
             */
            "SUNDAY" = 7,
        }
    }

    export default GDesktopEnums
}