
/// <reference path="./GLib-2.0.d.ts" />
/// <reference path="./GModule-2.0.d.ts" />
/// <reference path="./GObject-2.0.d.ts" />
/// <reference path="./Gio-2.0.d.ts" />
/// <reference path="./GdkPixbuf-2.0.d.ts" />

/**
 * Type Definitions for GJS (https://gjs.guide/), generated by [GirGen](https://github.com/aylur/girgen)
 * If you found a bug, create a bug report on [GirGen's Repository](https://github.com/aylur/girgen/issues/new)
 */
declare module "gi://GdkPixdata?version=2.0" {
    import type GLib from "gi://GLib?version=2.0"
    import type GModule from "gi://GModule?version=2.0"
    import type GObject from "gi://GObject?version=2.0"
    import type Gio from "gi://Gio?version=2.0"
    import type GdkPixbuf from "gi://GdkPixbuf?version=2.0"

    


    namespace GdkPixdata {
        const __name__: "GdkPixdata"
        const __version: "2.0"
        /**
         * A pixel buffer suitable for serialization and streaming.
         *
         * Using `GdkPixdata`, images can be compiled into an application,
         * making it unnecessary to refer to external image files at runtime.
         *
         * `GdkPixbuf` includes a utility named `gdk-pixbuf-csource`, which
         * can be used to convert image files into `GdkPixdata` structures suitable
         * for inclusion in C sources. To convert the `GdkPixdata` structures back
         * into a `GdkPixbuf`, use `gdk_pixbuf_from_pixdata()`.
         * @deprecated since 2.32 `GdkPixdata` should not be used any more. `GResource`   should be used to save the original compressed images inside the   program's binary
         */
        abstract class Pixdata {
            static readonly $gtype: GObject.GType<Pixdata>

            
            /**
             * magic number. A valid `GdkPixdata` structure must have
             *   `GDK_PIXBUF_MAGIC_NUMBER` here
             */
            magic: number
            /**
             * less than 1 to disable length checks, otherwise
             *   `GDK_PIXDATA_HEADER_LENGTH` plus the length of `pixel_data`
             */
            length: number
            /**
             * information about colorspace, sample width and
             *   encoding, in a `GdkPixdataType`
             */
            pixdata_type: number
            /**
             * Distance in bytes between rows
             */
            rowstride: number
            /**
             * Width of the image in pixels
             */
            width: number
            /**
             * Height of the image in pixels
             */
            height: number
            /**
             * `width` x `height`
             *   pixels, encoded according to `pixdata_type` and `rowstride`
             */
            pixel_data: Uint8Array
            /**
             * Deserializes (reconstruct) a #GdkPixdata structure from a byte stream.
             *
             * The byte stream consists of a straightforward writeout of the
             * `GdkPixdata` fields in network byte order, plus the `pixel_data`
             * bytes the structure points to.
             *
             * The `pixdata` contents are reconstructed byte by byte and are checked
             * for validity.
             *
             * This function may fail with `GDK_PIXBUF_ERROR_CORRUPT_IMAGE`
             * or `GDK_PIXBUF_ERROR_UNKNOWN_TYPE`.
             * @throws {GLib.Error}
             * @deprecated since 2.32 Use `GResource` instead.
             * @param stream stream of bytes containing a
              serialized #GdkPixdata structure.
             * @returns Upon successful deserialization `TRUE` is returned, `FALSE` otherwise.
             */
            deserialize(stream: Uint8Array): boolean
            /**
             * Serializes a #GdkPixdata structure into a byte stream.
             * The byte stream consists of a straightforward writeout of the
             * #GdkPixdata fields in network byte order, plus the @pixel_data
             * bytes the structure points to.
             * @deprecated since 2.32 Use #GResource instead.
             * @returns A newly-allocated string containing the serialized #GdkPixdata structure.
             */
            serialize(): Uint8Array
            /**
             * Generates C source code suitable for compiling images directly
             * into programs.
             *
             * GdkPixbuf ships with a program called `gdk-pixbuf-csource`, which offers
             * a command line interface to this function.
             * @deprecated since 2.32 Use #GResource instead.
             * @param name used for naming generated data structures or macros
             * @param dump_type the kind of C source to be generated
             * @returns a newly-allocated string buffer containing   the C source form of `pixdata`.
             */
            to_csource(name: string, dump_type: PixdataDumpType): GLib.String
        }
        /**
         * Converts a `GdkPixdata` to a `GdkPixbuf`.
         *
         * If `copy_pixels` is `TRUE` or if the pixel data is run-length-encoded,
         * the pixel data is copied into newly-allocated memory; otherwise it is
         * reused.
         * @throws {GLib.Error}
         * @deprecated since 2.32 Use `GResource` instead.
         * @param pixdata a #GdkPixdata to convert into a `GdkPixbuf`.
         * @param copy_pixels whether to copy raw pixel data; run-length encoded
          pixel data is always copied.
         * @returns a new pixbuf
         */
        function pixbuf_from_pixdata(pixdata: Pixdata, copy_pixels: boolean): GdkPixbuf.Pixbuf
        const PIXBUF_MAGIC_NUMBER: 1197763408
        const PIXDATA_HEADER_LENGTH: 24
        
        namespace PixdataDumpType {
            const $gtype: GObject.GType<PixdataDumpType>
        }

        /**
         * An enumeration which is used by gdk_pixdata_to_csource() to
         * determine the form of C source to be generated. The three values
         * @GDK_PIXDATA_DUMP_PIXDATA_STREAM, @GDK_PIXDATA_DUMP_PIXDATA_STRUCT
         * and @GDK_PIXDATA_DUMP_MACROS are mutually exclusive, as are
         * @GDK_PIXBUF_DUMP_GTYPES and @GDK_PIXBUF_DUMP_CTYPES. The remaining
         * elements are optional flags that can be freely added.
         * @deprecated since 2.32
         */
        enum PixdataDumpType {
            /**
             * Generate pixbuf data stream (a single
             *    string containing a serialized #GdkPixdata structure in network byte
             *    order).
             */
            "PIXDATA_STREAM" = 0,
            /**
             * Generate #GdkPixdata structure (needs
             *    the #GdkPixdata structure definition from gdk-pixdata.h).
             */
            "PIXDATA_STRUCT" = 1,
            /**
             *
             *    macro definitions for the image.
             */
            "MACROS" = 2,
            /**
             * Generate GLib data types instead of
             *    standard C data types.
             */
            "GTYPES" = 0,
            /**
             * Generate standard C data types instead of
             *    GLib data types.
             */
            "CTYPES" = 256,
            /**
             * Generate static symbols.
             */
            "STATIC" = 512,
            /**
             * Generate const symbols.
             */
            "CONST" = 1024,
            /**
             *
             *    macro definition  to  decode  run-length encoded image data.
             */
            "RLE_DECODER" = 65536,
        }
        
        namespace PixdataType {
            const $gtype: GObject.GType<PixdataType>
        }

        /**
         * An enumeration containing three sets of flags for a #GdkPixdata struct:
         * one for the used colorspace, one for the width of the samples and one
         * for the encoding of the pixel data.
         * @deprecated since 2.32
         */
        enum PixdataType {
            /**
             * each pixel has red, green and blue samples.
             */
            "COLOR_TYPE_RGB" = 1,
            /**
             * each pixel has red, green and blue samples
             *    and an alpha value.
             */
            "COLOR_TYPE_RGBA" = 2,
            /**
             * mask for the colortype flags of the enum.
             */
            "COLOR_TYPE_MASK" = 255,
            /**
             * each sample has 8 bits.
             */
            "SAMPLE_WIDTH_8" = 65536,
            /**
             * mask for the sample width flags of the enum.
             */
            "SAMPLE_WIDTH_MASK" = 983040,
            /**
             * the pixel data is in raw form.
             */
            "ENCODING_RAW" = 16777216,
            /**
             * the pixel data is run-length encoded. Runs may
             *    be up to 127 bytes long; their length is stored in a single byte
             *    preceding the pixel data for the run. If a run is constant, its length
             *    byte has the high bit set and the pixel data consists of a single pixel
             *    which must be repeated.
             */
            "ENCODING_RLE" = 33554432,
            /**
             * mask for the encoding flags of the enum.
             */
            "ENCODING_MASK" = 251658240,
        }
    }

    export default GdkPixdata
}