
/// <reference path="./GLib-2.0.d.ts" />
/// <reference path="./GModule-2.0.d.ts" />
/// <reference path="./GObject-2.0.d.ts" />
/// <reference path="./Gio-2.0.d.ts" />

/**
 * Type Definitions for GJS (https://gjs.guide/), generated by [GirGen](https://github.com/aylur/girgen)
 * If you found a bug, create a bug report on [GirGen's Repository](https://github.com/aylur/girgen/issues/new)
 */
declare module "gi://Geoclue?version=2.0" {
    import type GLib from "gi://GLib?version=2.0"
    import type GModule from "gi://GModule?version=2.0"
    import type GObject from "gi://GObject?version=2.0"
    import type Gio from "gi://Gio?version=2.0"

    


    namespace Geoclue {
        const __name__: "Geoclue"
        const __version: "2.0"
        

        namespace Client {
            interface SignalSignatures  {
                /**
                 *  D-Bus method.
                 *
                 * If a signal handler returns %TRUE, it means the signal handler will handle the invocation (e.g. take a reference to @invocation and eventually call gclue_client_complete_start() or e.g. g_dbus_method_invocation_return_error() on it) and no other signal handlers will run. If no signal handler handles the invocation, the %G_DBUS_ERROR_UNKNOWN_METHOD error is returned.
                 * @param invocation A #GDBusMethodInvocation.
                 * @returns %G_DBUS_METHOD_INVOCATION_HANDLED or %TRUE if the invocation was handled, %G_DBUS_METHOD_INVOCATION_UNHANDLED or %FALSE to let other signal handlers run.
                 */
                "handle-start"(invocation: Gio.DBusMethodInvocation): boolean
                /**
                 *  D-Bus method.
                 *
                 * If a signal handler returns %TRUE, it means the signal handler will handle the invocation (e.g. take a reference to @invocation and eventually call gclue_client_complete_stop() or e.g. g_dbus_method_invocation_return_error() on it) and no other signal handlers will run. If no signal handler handles the invocation, the %G_DBUS_ERROR_UNKNOWN_METHOD error is returned.
                 * @param invocation A #GDBusMethodInvocation.
                 * @returns %G_DBUS_METHOD_INVOCATION_HANDLED or %TRUE if the invocation was handled, %G_DBUS_METHOD_INVOCATION_UNHANDLED or %FALSE to let other signal handlers run.
                 */
                "handle-stop"(invocation: Gio.DBusMethodInvocation): boolean
                /**
                 *  is received.
                 *
                 * On the service-side, this signal can be used with e.g. g_signal_emit_by_name() to make the object emit the D-Bus signal.
                 * @param arg_old Argument.
                 * @param arg_new Argument.
                 */
                "location-updated"(arg_old: string, arg_new: string): void
            }

            interface ReadableProperties  {
                "active": boolean
                "desktop-id": string | null
                "distance-threshold": number
                "location": string | null
                "requested-accuracy-level": number
                "time-threshold": number
            }

            interface WritableProperties  {
                "active": boolean
                "desktop-id": string | null
                "distance-threshold": number
                "location": string | null
                "requested-accuracy-level": number
                "time-threshold": number
            }

            interface ConstructOnlyProperties  {
            }

            interface Interface  {
                /**
                 * Handler for the #GClueClient::handle-start signal.
                 * @param invocation
                 */
                vfunc_handle_start(invocation: Gio.DBusMethodInvocation): boolean
                /**
                 * Handler for the #GClueClient::handle-stop signal.
                 * @param invocation
                 */
                vfunc_handle_stop(invocation: Gio.DBusMethodInvocation): boolean
                /**
                 * Handler for the #GClueClient::location-updated signal.
                 * @param arg_old
                 * @param arg_new
                 */
                vfunc_location_updated(arg_old: string, arg_new: string): void
            }
        }

        /**
         * .
         */
        interface Client extends Client.Interface {
            readonly $signals: Client.SignalSignatures
            readonly $readableProperties: Client.ReadableProperties
            readonly $writableProperties: Client.WritableProperties
            readonly $constructOnlyProperties: Client.ConstructOnlyProperties
            /**
             * .
             *
             * Since the D-Bus property for this #GObject property is readable but not writable, it is meaningful to read from it on both the client- and service-side. It is only meaningful, however, to write to it on the service-side.
             * @default FALSE
             */
            get active(): boolean
            set active(value: boolean)
            /**
             * .
             *
             * Since the D-Bus property for this #GObject property is both readable and writable, it is meaningful to both read from it and write to it on both the service- and client-side.
             * @default NULL
             */
            get desktopId(): string | null
            set desktopId(value: string | null)
            /**
             * .
             *
             * Since the D-Bus property for this #GObject property is both readable and writable, it is meaningful to both read from it and write to it on both the service- and client-side.
             * @default 0
             */
            get distanceThreshold(): number
            set distanceThreshold(value: number)
            /**
             * .
             *
             * Since the D-Bus property for this #GObject property is readable but not writable, it is meaningful to read from it on both the client- and service-side. It is only meaningful, however, to write to it on the service-side.
             * @default NULL
             */
            get location(): string | null
            set location(value: string | null)
            /**
             * .
             *
             * Since the D-Bus property for this #GObject property is both readable and writable, it is meaningful to both read from it and write to it on both the service- and client-side.
             * @default 0
             */
            get requestedAccuracyLevel(): number
            set requestedAccuracyLevel(value: number)
            /**
             * .
             *
             * Since the D-Bus property for this #GObject property is both readable and writable, it is meaningful to both read from it and write to it on both the service- and client-side.
             * @default 0
             */
            get timeThreshold(): number
            set timeThreshold(value: number)
            /**
             *  D-Bus method on @proxy.
             * When the operation is finished, @callback will be invoked in the thread-default main loop of the thread you are calling this method from (see g_main_context_push_thread_default()).
             * You can then call gclue_client_call_start_finish() to get the result of the operation.
             *
             * See gclue_client_call_start_sync() for the synchronous, blocking version of this method.
             * @param cancellable A #GCancellable or %NULL.
             * @param callback A #GAsyncReadyCallback to call when the request is satisfied or %NULL.
             */
            call_start(cancellable: Gio.Cancellable | null, callback: Gio.AsyncReadyCallback | null): void
            /**
             * Finishes an operation started with gclue_client_call_start().
             * @throws {GLib.Error}
             * @param res The #GAsyncResult obtained from the #GAsyncReadyCallback passed to gclue_client_call_start().
             * @returns %TRUE if the call succeeded, %FALSE if `error` is set.
             */
            call_start_finish(res: Gio.AsyncResult): boolean
            /**
             *  D-Bus method on @proxy. The calling thread is blocked until a reply is received.
             *
             * See gclue_client_call_start() for the asynchronous version of this method.
             * @throws {GLib.Error}
             * @param cancellable A #GCancellable or %NULL.
             * @returns %TRUE if the call succeeded, %FALSE if `error` is set.
             */
            call_start_sync(cancellable: Gio.Cancellable | null): boolean
            /**
             *  D-Bus method on @proxy.
             * When the operation is finished, @callback will be invoked in the thread-default main loop of the thread you are calling this method from (see g_main_context_push_thread_default()).
             * You can then call gclue_client_call_stop_finish() to get the result of the operation.
             *
             * See gclue_client_call_stop_sync() for the synchronous, blocking version of this method.
             * @param cancellable A #GCancellable or %NULL.
             * @param callback A #GAsyncReadyCallback to call when the request is satisfied or %NULL.
             */
            call_stop(cancellable: Gio.Cancellable | null, callback: Gio.AsyncReadyCallback | null): void
            /**
             * Finishes an operation started with gclue_client_call_stop().
             * @throws {GLib.Error}
             * @param res The #GAsyncResult obtained from the #GAsyncReadyCallback passed to gclue_client_call_stop().
             * @returns %TRUE if the call succeeded, %FALSE if `error` is set.
             */
            call_stop_finish(res: Gio.AsyncResult): boolean
            /**
             *  D-Bus method on @proxy. The calling thread is blocked until a reply is received.
             *
             * See gclue_client_call_stop() for the asynchronous version of this method.
             * @throws {GLib.Error}
             * @param cancellable A #GCancellable or %NULL.
             * @returns %TRUE if the call succeeded, %FALSE if `error` is set.
             */
            call_stop_sync(cancellable: Gio.Cancellable | null): boolean
            /**
             *  D-Bus method. If you instead want to finish handling an invocation by returning an error, use g_dbus_method_invocation_return_error() or similar.
             *
             * This method will free @invocation, you cannot use it afterwards.
             * @param invocation A #GDBusMethodInvocation.
             */
            complete_start(invocation: Gio.DBusMethodInvocation): void
            /**
             *  D-Bus method. If you instead want to finish handling an invocation by returning an error, use g_dbus_method_invocation_return_error() or similar.
             *
             * This method will free @invocation, you cannot use it afterwards.
             * @param invocation A #GDBusMethodInvocation.
             */
            complete_stop(invocation: Gio.DBusMethodInvocation): void
            /**
             *  D-Bus signal.
             * @param arg_old Argument to pass with the signal.
             * @param arg_new Argument to pass with the signal.
             */
            emit_location_updated(arg_old: string, arg_new: string): void
        }


        interface ClientIface {
            readonly $gtype: GObject.GType<Client>
            readonly prototype: Client
            /**
             *  D-Bus interface.
             * @returns A #GDBusInterfaceInfo. Do not free.
             */
            interface_info(): Gio.DBusInterfaceInfo
            /**
             * Overrides all #GObject properties in the #GClueClient interface for a concrete class.
             * The properties are overridden in the order they are defined.
             * @param klass The class structure for a #GObject derived class.
             * @param property_id_begin The property id to assign to the first overridden property.
             * @returns The last property id.
             */
            override_properties(klass: GObject.ObjectClass, property_id_begin: number): number

            [Symbol.hasInstance](instance: unknown): instance is Client
        }

        const Client: ClientIface
        

        namespace Location {
            interface SignalSignatures  {
            }

            interface ReadableProperties  {
                "accuracy": number
                "altitude": number
                "description": string | null
                "heading": number
                "latitude": number
                "longitude": number
                "speed": number
                "timestamp": GLib.Variant | null
            }

            interface WritableProperties  {
                "accuracy": number
                "altitude": number
                "description": string | null
                "heading": number
                "latitude": number
                "longitude": number
                "speed": number
                "timestamp": GLib.Variant | null
            }

            interface ConstructOnlyProperties  {
            }

            interface Interface  {
            }
        }

        /**
         * .
         */
        interface Location extends Location.Interface {
            readonly $signals: Location.SignalSignatures
            readonly $readableProperties: Location.ReadableProperties
            readonly $writableProperties: Location.WritableProperties
            readonly $constructOnlyProperties: Location.ConstructOnlyProperties
            /**
             * .
             *
             * Since the D-Bus property for this #GObject property is readable but not writable, it is meaningful to read from it on both the client- and service-side. It is only meaningful, however, to write to it on the service-side.
             * @default 0.000000
             */
            get accuracy(): number
            set accuracy(value: number)
            /**
             * .
             *
             * Since the D-Bus property for this #GObject property is readable but not writable, it is meaningful to read from it on both the client- and service-side. It is only meaningful, however, to write to it on the service-side.
             * @default 0.000000
             */
            get altitude(): number
            set altitude(value: number)
            /**
             * .
             *
             * Since the D-Bus property for this #GObject property is readable but not writable, it is meaningful to read from it on both the client- and service-side. It is only meaningful, however, to write to it on the service-side.
             * @default NULL
             */
            get description(): string | null
            set description(value: string | null)
            /**
             * .
             *
             * Since the D-Bus property for this #GObject property is readable but not writable, it is meaningful to read from it on both the client- and service-side. It is only meaningful, however, to write to it on the service-side.
             * @default 0.000000
             */
            get heading(): number
            set heading(value: number)
            /**
             * .
             *
             * Since the D-Bus property for this #GObject property is readable but not writable, it is meaningful to read from it on both the client- and service-side. It is only meaningful, however, to write to it on the service-side.
             * @default 0.000000
             */
            get latitude(): number
            set latitude(value: number)
            /**
             * .
             *
             * Since the D-Bus property for this #GObject property is readable but not writable, it is meaningful to read from it on both the client- and service-side. It is only meaningful, however, to write to it on the service-side.
             * @default 0.000000
             */
            get longitude(): number
            set longitude(value: number)
            /**
             * .
             *
             * Since the D-Bus property for this #GObject property is readable but not writable, it is meaningful to read from it on both the client- and service-side. It is only meaningful, however, to write to it on the service-side.
             * @default 0.000000
             */
            get speed(): number
            set speed(value: number)
            /**
             * .
             *
             * Since the D-Bus property for this #GObject property is readable but not writable, it is meaningful to read from it on both the client- and service-side. It is only meaningful, however, to write to it on the service-side.
             */
            get timestamp(): GLib.Variant | null
            set timestamp(value: GLib.Variant | null)
        }


        interface LocationIface {
            readonly $gtype: GObject.GType<Location>
            readonly prototype: Location
            /**
             *  D-Bus interface.
             * @returns A #GDBusInterfaceInfo. Do not free.
             */
            interface_info(): Gio.DBusInterfaceInfo
            /**
             * Overrides all #GObject properties in the #GClueLocation interface for a concrete class.
             * The properties are overridden in the order they are defined.
             * @param klass The class structure for a #GObject derived class.
             * @param property_id_begin The property id to assign to the first overridden property.
             * @returns The last property id.
             */
            override_properties(klass: GObject.ObjectClass, property_id_begin: number): number

            [Symbol.hasInstance](instance: unknown): instance is Location
        }

        const Location: LocationIface
        

        namespace Manager {
            interface SignalSignatures  {
                /**
                 *  D-Bus method.
                 *
                 * If a signal handler returns %TRUE, it means the signal handler will handle the invocation (e.g. take a reference to @invocation and eventually call gclue_manager_complete_add_agent() or e.g. g_dbus_method_invocation_return_error() on it) and no other signal handlers will run. If no signal handler handles the invocation, the %G_DBUS_ERROR_UNKNOWN_METHOD error is returned.
                 * @param invocation A #GDBusMethodInvocation.
                 * @param arg_id Argument passed by remote caller.
                 * @returns %G_DBUS_METHOD_INVOCATION_HANDLED or %TRUE if the invocation was handled, %G_DBUS_METHOD_INVOCATION_UNHANDLED or %FALSE to let other signal handlers run.
                 */
                "handle-add-agent"(invocation: Gio.DBusMethodInvocation, arg_id: string): boolean
                /**
                 *  D-Bus method.
                 *
                 * If a signal handler returns %TRUE, it means the signal handler will handle the invocation (e.g. take a reference to @invocation and eventually call gclue_manager_complete_create_client() or e.g. g_dbus_method_invocation_return_error() on it) and no other signal handlers will run. If no signal handler handles the invocation, the %G_DBUS_ERROR_UNKNOWN_METHOD error is returned.
                 * @param invocation A #GDBusMethodInvocation.
                 * @returns %G_DBUS_METHOD_INVOCATION_HANDLED or %TRUE if the invocation was handled, %G_DBUS_METHOD_INVOCATION_UNHANDLED or %FALSE to let other signal handlers run.
                 */
                "handle-create-client"(invocation: Gio.DBusMethodInvocation): boolean
                /**
                 *  D-Bus method.
                 *
                 * If a signal handler returns %TRUE, it means the signal handler will handle the invocation (e.g. take a reference to @invocation and eventually call gclue_manager_complete_delete_client() or e.g. g_dbus_method_invocation_return_error() on it) and no other signal handlers will run. If no signal handler handles the invocation, the %G_DBUS_ERROR_UNKNOWN_METHOD error is returned.
                 * @param invocation A #GDBusMethodInvocation.
                 * @param arg_client Argument passed by remote caller.
                 * @returns %G_DBUS_METHOD_INVOCATION_HANDLED or %TRUE if the invocation was handled, %G_DBUS_METHOD_INVOCATION_UNHANDLED or %FALSE to let other signal handlers run.
                 */
                "handle-delete-client"(invocation: Gio.DBusMethodInvocation, arg_client: string): boolean
                /**
                 *  D-Bus method.
                 *
                 * If a signal handler returns %TRUE, it means the signal handler will handle the invocation (e.g. take a reference to @invocation and eventually call gclue_manager_complete_get_client() or e.g. g_dbus_method_invocation_return_error() on it) and no other signal handlers will run. If no signal handler handles the invocation, the %G_DBUS_ERROR_UNKNOWN_METHOD error is returned.
                 * @param invocation A #GDBusMethodInvocation.
                 * @returns %G_DBUS_METHOD_INVOCATION_HANDLED or %TRUE if the invocation was handled, %G_DBUS_METHOD_INVOCATION_UNHANDLED or %FALSE to let other signal handlers run.
                 */
                "handle-get-client"(invocation: Gio.DBusMethodInvocation): boolean
            }

            interface ReadableProperties  {
                "available-accuracy-level": number
                "in-use": boolean
            }

            interface WritableProperties  {
                "available-accuracy-level": number
                "in-use": boolean
            }

            interface ConstructOnlyProperties  {
            }

            interface Interface  {
                /**
                 * Handler for the #GClueManager::handle-add-agent signal.
                 * @param invocation
                 * @param arg_id
                 */
                vfunc_handle_add_agent(invocation: Gio.DBusMethodInvocation, arg_id: string): boolean
                /**
                 * Handler for the #GClueManager::handle-create-client signal.
                 * @param invocation
                 */
                vfunc_handle_create_client(invocation: Gio.DBusMethodInvocation): boolean
                /**
                 * Handler for the #GClueManager::handle-delete-client signal.
                 * @param invocation
                 * @param arg_client
                 */
                vfunc_handle_delete_client(invocation: Gio.DBusMethodInvocation, arg_client: string): boolean
                /**
                 * Handler for the #GClueManager::handle-get-client signal.
                 * @param invocation
                 */
                vfunc_handle_get_client(invocation: Gio.DBusMethodInvocation): boolean
            }
        }

        /**
         * .
         */
        interface Manager extends Manager.Interface {
            readonly $signals: Manager.SignalSignatures
            readonly $readableProperties: Manager.ReadableProperties
            readonly $writableProperties: Manager.WritableProperties
            readonly $constructOnlyProperties: Manager.ConstructOnlyProperties
            /**
             * .
             *
             * Since the D-Bus property for this #GObject property is readable but not writable, it is meaningful to read from it on both the client- and service-side. It is only meaningful, however, to write to it on the service-side.
             * @default 0
             */
            get availableAccuracyLevel(): number
            set availableAccuracyLevel(value: number)
            /**
             * .
             *
             * Since the D-Bus property for this #GObject property is readable but not writable, it is meaningful to read from it on both the client- and service-side. It is only meaningful, however, to write to it on the service-side.
             * @default FALSE
             */
            get inUse(): boolean
            set inUse(value: boolean)
            /**
             *  D-Bus method on @proxy.
             * When the operation is finished, @callback will be invoked in the thread-default main loop of the thread you are calling this method from (see g_main_context_push_thread_default()).
             * You can then call gclue_manager_call_add_agent_finish() to get the result of the operation.
             *
             * See gclue_manager_call_add_agent_sync() for the synchronous, blocking version of this method.
             * @param arg_id Argument to pass with the method invocation.
             * @param cancellable A #GCancellable or %NULL.
             * @param callback A #GAsyncReadyCallback to call when the request is satisfied or %NULL.
             */
            call_add_agent(arg_id: string, cancellable: Gio.Cancellable | null, callback: Gio.AsyncReadyCallback | null): void
            /**
             * Finishes an operation started with gclue_manager_call_add_agent().
             * @throws {GLib.Error}
             * @param res The #GAsyncResult obtained from the #GAsyncReadyCallback passed to gclue_manager_call_add_agent().
             * @returns %TRUE if the call succeeded, %FALSE if `error` is set.
             */
            call_add_agent_finish(res: Gio.AsyncResult): boolean
            /**
             *  D-Bus method on @proxy. The calling thread is blocked until a reply is received.
             *
             * See gclue_manager_call_add_agent() for the asynchronous version of this method.
             * @throws {GLib.Error}
             * @param arg_id Argument to pass with the method invocation.
             * @param cancellable A #GCancellable or %NULL.
             * @returns %TRUE if the call succeeded, %FALSE if `error` is set.
             */
            call_add_agent_sync(arg_id: string, cancellable: Gio.Cancellable | null): boolean
            /**
             *  D-Bus method on @proxy.
             * When the operation is finished, @callback will be invoked in the thread-default main loop of the thread you are calling this method from (see g_main_context_push_thread_default()).
             * You can then call gclue_manager_call_create_client_finish() to get the result of the operation.
             *
             * See gclue_manager_call_create_client_sync() for the synchronous, blocking version of this method.
             * @param cancellable A #GCancellable or %NULL.
             * @param callback A #GAsyncReadyCallback to call when the request is satisfied or %NULL.
             */
            call_create_client(cancellable: Gio.Cancellable | null, callback: Gio.AsyncReadyCallback | null): void
            /**
             * Finishes an operation started with gclue_manager_call_create_client().
             * @throws {GLib.Error}
             * @param res The #GAsyncResult obtained from the #GAsyncReadyCallback passed to gclue_manager_call_create_client().
             * @returns %TRUE if the call succeeded, %FALSE if `error` is set., Return location for return parameter or %NULL to ignore.
             */
            call_create_client_finish(res: Gio.AsyncResult): boolean
            /**
             *  D-Bus method on @proxy. The calling thread is blocked until a reply is received.
             *
             * See gclue_manager_call_create_client() for the asynchronous version of this method.
             * @throws {GLib.Error}
             * @param cancellable A #GCancellable or %NULL.
             * @returns %TRUE if the call succeeded, %FALSE if `error` is set., Return location for return parameter or %NULL to ignore.
             */
            call_create_client_sync(cancellable: Gio.Cancellable | null): boolean
            /**
             *  D-Bus method on @proxy.
             * When the operation is finished, @callback will be invoked in the thread-default main loop of the thread you are calling this method from (see g_main_context_push_thread_default()).
             * You can then call gclue_manager_call_delete_client_finish() to get the result of the operation.
             *
             * See gclue_manager_call_delete_client_sync() for the synchronous, blocking version of this method.
             * @param arg_client Argument to pass with the method invocation.
             * @param cancellable A #GCancellable or %NULL.
             * @param callback A #GAsyncReadyCallback to call when the request is satisfied or %NULL.
             */
            call_delete_client(arg_client: string, cancellable: Gio.Cancellable | null, callback: Gio.AsyncReadyCallback | null): void
            /**
             * Finishes an operation started with gclue_manager_call_delete_client().
             * @throws {GLib.Error}
             * @param res The #GAsyncResult obtained from the #GAsyncReadyCallback passed to gclue_manager_call_delete_client().
             * @returns %TRUE if the call succeeded, %FALSE if `error` is set.
             */
            call_delete_client_finish(res: Gio.AsyncResult): boolean
            /**
             *  D-Bus method on @proxy. The calling thread is blocked until a reply is received.
             *
             * See gclue_manager_call_delete_client() for the asynchronous version of this method.
             * @throws {GLib.Error}
             * @param arg_client Argument to pass with the method invocation.
             * @param cancellable A #GCancellable or %NULL.
             * @returns %TRUE if the call succeeded, %FALSE if `error` is set.
             */
            call_delete_client_sync(arg_client: string, cancellable: Gio.Cancellable | null): boolean
            /**
             *  D-Bus method on @proxy.
             * When the operation is finished, @callback will be invoked in the thread-default main loop of the thread you are calling this method from (see g_main_context_push_thread_default()).
             * You can then call gclue_manager_call_get_client_finish() to get the result of the operation.
             *
             * See gclue_manager_call_get_client_sync() for the synchronous, blocking version of this method.
             * @param cancellable A #GCancellable or %NULL.
             * @param callback A #GAsyncReadyCallback to call when the request is satisfied or %NULL.
             */
            call_get_client(cancellable: Gio.Cancellable | null, callback: Gio.AsyncReadyCallback | null): void
            /**
             * Finishes an operation started with gclue_manager_call_get_client().
             * @throws {GLib.Error}
             * @param res The #GAsyncResult obtained from the #GAsyncReadyCallback passed to gclue_manager_call_get_client().
             * @returns %TRUE if the call succeeded, %FALSE if `error` is set., Return location for return parameter or %NULL to ignore.
             */
            call_get_client_finish(res: Gio.AsyncResult): boolean
            /**
             *  D-Bus method on @proxy. The calling thread is blocked until a reply is received.
             *
             * See gclue_manager_call_get_client() for the asynchronous version of this method.
             * @throws {GLib.Error}
             * @param cancellable A #GCancellable or %NULL.
             * @returns %TRUE if the call succeeded, %FALSE if `error` is set., Return location for return parameter or %NULL to ignore.
             */
            call_get_client_sync(cancellable: Gio.Cancellable | null): boolean
            /**
             *  D-Bus method. If you instead want to finish handling an invocation by returning an error, use g_dbus_method_invocation_return_error() or similar.
             *
             * This method will free @invocation, you cannot use it afterwards.
             * @param invocation A #GDBusMethodInvocation.
             */
            complete_add_agent(invocation: Gio.DBusMethodInvocation): void
            /**
             *  D-Bus method. If you instead want to finish handling an invocation by returning an error, use g_dbus_method_invocation_return_error() or similar.
             *
             * This method will free @invocation, you cannot use it afterwards.
             * @param invocation A #GDBusMethodInvocation.
             * @param client Parameter to return.
             */
            complete_create_client(invocation: Gio.DBusMethodInvocation, client: string): void
            /**
             *  D-Bus method. If you instead want to finish handling an invocation by returning an error, use g_dbus_method_invocation_return_error() or similar.
             *
             * This method will free @invocation, you cannot use it afterwards.
             * @param invocation A #GDBusMethodInvocation.
             */
            complete_delete_client(invocation: Gio.DBusMethodInvocation): void
            /**
             *  D-Bus method. If you instead want to finish handling an invocation by returning an error, use g_dbus_method_invocation_return_error() or similar.
             *
             * This method will free @invocation, you cannot use it afterwards.
             * @param invocation A #GDBusMethodInvocation.
             * @param client Parameter to return.
             */
            complete_get_client(invocation: Gio.DBusMethodInvocation, client: string): void
        }


        interface ManagerIface {
            readonly $gtype: GObject.GType<Manager>
            readonly prototype: Manager
            /**
             *  D-Bus interface.
             * @returns A #GDBusInterfaceInfo. Do not free.
             */
            interface_info(): Gio.DBusInterfaceInfo
            /**
             * Overrides all #GObject properties in the #GClueManager interface for a concrete class.
             * The properties are overridden in the order they are defined.
             * @param klass The class structure for a #GObject derived class.
             * @param property_id_begin The property id to assign to the first overridden property.
             * @returns The last property id.
             */
            override_properties(klass: GObject.ObjectClass, property_id_begin: number): number

            [Symbol.hasInstance](instance: unknown): instance is Manager
        }

        const Manager: ManagerIface
        

        namespace ClientProxy {
            interface SignalSignatures extends Gio.DBusProxy.SignalSignatures, Client.SignalSignatures, Gio.AsyncInitable.SignalSignatures, Gio.DBusInterface.SignalSignatures, Gio.Initable.SignalSignatures {
            }

            interface ReadableProperties extends Gio.DBusProxy.ReadableProperties, Client.ReadableProperties, Gio.AsyncInitable.ReadableProperties, Gio.DBusInterface.ReadableProperties, Gio.Initable.ReadableProperties {
            }

            interface WritableProperties extends Gio.DBusProxy.WritableProperties, Client.WritableProperties, Gio.AsyncInitable.WritableProperties, Gio.DBusInterface.WritableProperties, Gio.Initable.WritableProperties {
            }

            interface ConstructOnlyProperties extends Gio.DBusProxy.ConstructOnlyProperties, Client.ConstructOnlyProperties, Gio.AsyncInitable.ConstructOnlyProperties, Gio.DBusInterface.ConstructOnlyProperties, Gio.Initable.ConstructOnlyProperties {
            }
        }

        /**
         * The #GClueClientProxy structure contains only private data and should only be accessed using the provided API.
         */
        interface ClientProxy extends Gio.DBusProxy, Client, Gio.AsyncInitable, Gio.DBusInterface, Gio.Initable {
            readonly $signals: ClientProxy.SignalSignatures
            readonly $readableProperties: ClientProxy.ReadableProperties
            readonly $writableProperties: ClientProxy.WritableProperties
            readonly $constructOnlyProperties: ClientProxy.ConstructOnlyProperties
        }

        interface ClientProxyClass extends Omit<Gio.DBusProxyClass, "new"> {
            readonly $gtype: GObject.GType<ClientProxy>
            readonly prototype: ClientProxy
            new (props?: Partial<GObject.ConstructorProps<ClientProxy>>): ClientProxy
            /**
             * Finishes an operation started with gclue_client_proxy_new().
             * @throws {GLib.Error}
             * @param res The #GAsyncResult obtained from the #GAsyncReadyCallback passed to gclue_client_proxy_new().
             * @returns The constructed proxy object or %NULL if `error` is set.
             */
            new_finish(res: Gio.AsyncResult): ClientProxy
            /**
             * Finishes an operation started with gclue_client_proxy_new_for_bus().
             * @throws {GLib.Error}
             * @param res The #GAsyncResult obtained from the #GAsyncReadyCallback passed to gclue_client_proxy_new_for_bus().
             * @returns The constructed proxy object or %NULL if `error` is set.
             */
            new_for_bus_finish(res: Gio.AsyncResult): ClientProxy
            /**
             * Like gclue_client_proxy_new_sync() but takes a #GBusType instead of a #GDBusConnection.
             *
             * The calling thread is blocked until a reply is received.
             *
             * See gclue_client_proxy_new_for_bus() for the asynchronous version of this constructor.
             * @throws {GLib.Error}
             * @param bus_type A #GBusType.
             * @param flags Flags from the #GDBusProxyFlags enumeration.
             * @param name A bus name (well-known or unique).
             * @param object_path An object path.
             * @param cancellable A #GCancellable or %NULL.
             * @returns The constructed proxy object or %NULL if `error` is set.
             */
            new_for_bus_sync(bus_type: Gio.BusType, flags: Gio.DBusProxyFlags, name: string, object_path: string, cancellable: Gio.Cancellable | null): ClientProxy
            /**
             * . See g_dbus_proxy_new_sync() for more details.
             *
             * The calling thread is blocked until a reply is received.
             *
             * See gclue_client_proxy_new() for the asynchronous version of this constructor.
             * @throws {GLib.Error}
             * @param connection A #GDBusConnection.
             * @param flags Flags from the #GDBusProxyFlags enumeration.
             * @param name A bus name (well-known or unique) or %NULL if @connection is not a message bus connection.
             * @param object_path An object path.
             * @param cancellable A #GCancellable or %NULL.
             * @returns The constructed proxy object or %NULL if `error` is set.
             */
            new_sync(connection: Gio.DBusConnection, flags: Gio.DBusProxyFlags, name: string | null, object_path: string, cancellable: Gio.Cancellable | null): ClientProxy
            /**
             * A utility function to create a #GClueClientProxy without having to deal with
             * a #GClueManager. See also gclue_client_proxy_create_full() which improves
             * resource management.
             *
             * This is identitcal to calling gclue_client_proxy_create_full() without any
             * flags set.
             *
             * See #gclue_client_proxy_create_sync() for the synchronous, blocking version
             * of this function.
             * @param desktop_id The desktop file id (the basename of the desktop file).
             * @param accuracy_level The requested accuracy level as #GClueAccuracyLevel.
             * @param cancellable A #GCancellable or %NULL.
             * @param callback A #GAsyncReadyCallback to call when the results are ready.
             */
            create(desktop_id: string, accuracy_level: AccuracyLevel, cancellable: Gio.Cancellable | null, callback: Gio.AsyncReadyCallback | null): void
            /**
             * Finishes an operation started with gclue_client_proxy_create().
             * @throws {GLib.Error}
             * @param result The #GAsyncResult obtained from the #GAsyncReadyCallback passed to
                     gclue_client_proxy_create().
             * @returns The constructed proxy object or %NULL if `error` is set.
             */
            create_finish(result: Gio.AsyncResult): ClientProxy
            /**
             * A utility function to create a #GClueClientProxy without having to deal with
             * a #GClueManager.
             *
             * By setting the #GCLUE_CLIENT_PROXY_CREATE_AUTO_DELETE flag you can ensure
             * that the client will be deleted again from the geoclue service when
             * it is destroyed. This flag should be used unless you are doing explicit
             * resource management.
             *
             * See #gclue_client_proxy_create_full_sync() for the synchronous, blocking
             * version of this function.
             * @param desktop_id The desktop file id (the basename of the desktop file).
             * @param accuracy_level The requested accuracy level as #GClueAccuracyLevel.
             * @param flags #GClueClientProxyCreateFlags to modify the creation.
             * @param cancellable A #GCancellable or %NULL.
             * @param callback A #GAsyncReadyCallback to call when the results are ready.
             */
            create_full(desktop_id: string, accuracy_level: AccuracyLevel, flags: ClientProxyCreateFlags, cancellable: Gio.Cancellable | null, callback: Gio.AsyncReadyCallback | null): void
            /**
             * Finishes an operation started with gclue_client_proxy_create_full().
             * @throws {GLib.Error}
             * @param result The #GAsyncResult obtained from the #GAsyncReadyCallback passed to
                     gclue_client_proxy_create().
             * @returns The constructed proxy object or %NULL if `error` is set.
             */
            create_full_finish(result: Gio.AsyncResult): ClientProxy
            /**
             * The synchronous and blocking version of #gclue_client_proxy_create_full().
             *
             * By setting the #GCLUE_CLIENT_PROXY_CREATE_AUTO_DELETE flag you can ensure
             * that the client will be deleted again from the geoclue service when
             * it is destroyed. This flag should be used unless you are doing explicit
             * resource management.
             * @throws {GLib.Error}
             * @param desktop_id The desktop file id (the basename of the desktop file).
             * @param accuracy_level The requested accuracy level as #GClueAccuracyLevel.
             * @param flags #GClueClientProxyCreateFlags to modify the creation.
             * @param cancellable A #GCancellable or %NULL.
             * @returns The constructed proxy object or %NULL if `error` is set.
             */
            create_full_sync(desktop_id: string, accuracy_level: AccuracyLevel, flags: ClientProxyCreateFlags, cancellable: Gio.Cancellable | null): ClientProxy
            /**
             * The synchronous and blocking version of #gclue_client_proxy_create().
             * See also gclue_client_proxy_create_full_sync() which improves resource
             * management.
             *
             * This function is identical to calling gclue_client_proxy_create_full_sync()
             * without any flags set.
             * @throws {GLib.Error}
             * @param desktop_id The desktop file id (the basename of the desktop file).
             * @param accuracy_level The requested accuracy level as #GClueAccuracyLevel.
             * @param cancellable A #GCancellable or %NULL.
             * @returns The constructed proxy object or %NULL if `error` is set.
             */
            create_sync(desktop_id: string, accuracy_level: AccuracyLevel, cancellable: Gio.Cancellable | null): ClientProxy
            /**
             * . See g_dbus_proxy_new() for more details.
             *
             * When the operation is finished, @callback will be invoked in the thread-default main loop of the thread you are calling this method from (see g_main_context_push_thread_default()).
             * You can then call gclue_client_proxy_new_finish() to get the result of the operation.
             *
             * See gclue_client_proxy_new_sync() for the synchronous, blocking version of this constructor.
             * @param connection A #GDBusConnection.
             * @param flags Flags from the #GDBusProxyFlags enumeration.
             * @param name A bus name (well-known or unique) or %NULL if @connection is not a message bus connection.
             * @param object_path An object path.
             * @param cancellable A #GCancellable or %NULL.
             * @param callback A #GAsyncReadyCallback to call when the request is satisfied.
             */
            "new"(connection: Gio.DBusConnection, flags: Gio.DBusProxyFlags, name: string | null, object_path: string, cancellable: Gio.Cancellable | null, callback: Gio.AsyncReadyCallback | null): void
            /**
             * Like gclue_client_proxy_new() but takes a #GBusType instead of a #GDBusConnection.
             *
             * When the operation is finished, @callback will be invoked in the thread-default main loop of the thread you are calling this method from (see g_main_context_push_thread_default()).
             * You can then call gclue_client_proxy_new_for_bus_finish() to get the result of the operation.
             *
             * See gclue_client_proxy_new_for_bus_sync() for the synchronous, blocking version of this constructor.
             * @param bus_type A #GBusType.
             * @param flags Flags from the #GDBusProxyFlags enumeration.
             * @param name A bus name (well-known or unique).
             * @param object_path An object path.
             * @param cancellable A #GCancellable or %NULL.
             * @param callback A #GAsyncReadyCallback to call when the request is satisfied.
             */
            new_for_bus(bus_type: Gio.BusType, flags: Gio.DBusProxyFlags, name: string, object_path: string, cancellable: Gio.Cancellable | null, callback: Gio.AsyncReadyCallback | null): void
        }

        const ClientProxy: ClientProxyClass
        

        namespace ClientSkeleton {
            interface SignalSignatures extends Gio.DBusInterfaceSkeleton.SignalSignatures, Client.SignalSignatures, Gio.DBusInterface.SignalSignatures {
            }

            interface ReadableProperties extends Gio.DBusInterfaceSkeleton.ReadableProperties, Client.ReadableProperties, Gio.DBusInterface.ReadableProperties {
            }

            interface WritableProperties extends Gio.DBusInterfaceSkeleton.WritableProperties, Client.WritableProperties, Gio.DBusInterface.WritableProperties {
            }

            interface ConstructOnlyProperties extends Gio.DBusInterfaceSkeleton.ConstructOnlyProperties, Client.ConstructOnlyProperties, Gio.DBusInterface.ConstructOnlyProperties {
            }
        }

        /**
         * The #GClueClientSkeleton structure contains only private data and should only be accessed using the provided API.
         */
        interface ClientSkeleton extends Gio.DBusInterfaceSkeleton, Client, Gio.DBusInterface {
            readonly $signals: ClientSkeleton.SignalSignatures
            readonly $readableProperties: ClientSkeleton.ReadableProperties
            readonly $writableProperties: ClientSkeleton.WritableProperties
            readonly $constructOnlyProperties: ClientSkeleton.ConstructOnlyProperties
        }

        interface ClientSkeletonClass extends Omit<Gio.DBusInterfaceSkeletonClass, "new"> {
            readonly $gtype: GObject.GType<ClientSkeleton>
            readonly prototype: ClientSkeleton
            new (props?: Partial<GObject.ConstructorProps<ClientSkeleton>>): ClientSkeleton
            /**
             * .
             * @returns The skeleton object.
             */
            "new"(): ClientSkeleton
        }

        const ClientSkeleton: ClientSkeletonClass
        

        namespace LocationProxy {
            interface SignalSignatures extends Gio.DBusProxy.SignalSignatures, Location.SignalSignatures, Gio.AsyncInitable.SignalSignatures, Gio.DBusInterface.SignalSignatures, Gio.Initable.SignalSignatures {
            }

            interface ReadableProperties extends Gio.DBusProxy.ReadableProperties, Location.ReadableProperties, Gio.AsyncInitable.ReadableProperties, Gio.DBusInterface.ReadableProperties, Gio.Initable.ReadableProperties {
            }

            interface WritableProperties extends Gio.DBusProxy.WritableProperties, Location.WritableProperties, Gio.AsyncInitable.WritableProperties, Gio.DBusInterface.WritableProperties, Gio.Initable.WritableProperties {
            }

            interface ConstructOnlyProperties extends Gio.DBusProxy.ConstructOnlyProperties, Location.ConstructOnlyProperties, Gio.AsyncInitable.ConstructOnlyProperties, Gio.DBusInterface.ConstructOnlyProperties, Gio.Initable.ConstructOnlyProperties {
            }
        }

        /**
         * The #GClueLocationProxy structure contains only private data and should only be accessed using the provided API.
         */
        interface LocationProxy extends Gio.DBusProxy, Location, Gio.AsyncInitable, Gio.DBusInterface, Gio.Initable {
            readonly $signals: LocationProxy.SignalSignatures
            readonly $readableProperties: LocationProxy.ReadableProperties
            readonly $writableProperties: LocationProxy.WritableProperties
            readonly $constructOnlyProperties: LocationProxy.ConstructOnlyProperties
        }

        interface LocationProxyClass extends Omit<Gio.DBusProxyClass, "new"> {
            readonly $gtype: GObject.GType<LocationProxy>
            readonly prototype: LocationProxy
            new (props?: Partial<GObject.ConstructorProps<LocationProxy>>): LocationProxy
            /**
             * Finishes an operation started with gclue_location_proxy_new().
             * @throws {GLib.Error}
             * @param res The #GAsyncResult obtained from the #GAsyncReadyCallback passed to gclue_location_proxy_new().
             * @returns The constructed proxy object or %NULL if `error` is set.
             */
            new_finish(res: Gio.AsyncResult): LocationProxy
            /**
             * Finishes an operation started with gclue_location_proxy_new_for_bus().
             * @throws {GLib.Error}
             * @param res The #GAsyncResult obtained from the #GAsyncReadyCallback passed to gclue_location_proxy_new_for_bus().
             * @returns The constructed proxy object or %NULL if `error` is set.
             */
            new_for_bus_finish(res: Gio.AsyncResult): LocationProxy
            /**
             * Like gclue_location_proxy_new_sync() but takes a #GBusType instead of a #GDBusConnection.
             *
             * The calling thread is blocked until a reply is received.
             *
             * See gclue_location_proxy_new_for_bus() for the asynchronous version of this constructor.
             * @throws {GLib.Error}
             * @param bus_type A #GBusType.
             * @param flags Flags from the #GDBusProxyFlags enumeration.
             * @param name A bus name (well-known or unique).
             * @param object_path An object path.
             * @param cancellable A #GCancellable or %NULL.
             * @returns The constructed proxy object or %NULL if `error` is set.
             */
            new_for_bus_sync(bus_type: Gio.BusType, flags: Gio.DBusProxyFlags, name: string, object_path: string, cancellable: Gio.Cancellable | null): LocationProxy
            /**
             * . See g_dbus_proxy_new_sync() for more details.
             *
             * The calling thread is blocked until a reply is received.
             *
             * See gclue_location_proxy_new() for the asynchronous version of this constructor.
             * @throws {GLib.Error}
             * @param connection A #GDBusConnection.
             * @param flags Flags from the #GDBusProxyFlags enumeration.
             * @param name A bus name (well-known or unique) or %NULL if @connection is not a message bus connection.
             * @param object_path An object path.
             * @param cancellable A #GCancellable or %NULL.
             * @returns The constructed proxy object or %NULL if `error` is set.
             */
            new_sync(connection: Gio.DBusConnection, flags: Gio.DBusProxyFlags, name: string | null, object_path: string, cancellable: Gio.Cancellable | null): LocationProxy
            /**
             * . See g_dbus_proxy_new() for more details.
             *
             * When the operation is finished, @callback will be invoked in the thread-default main loop of the thread you are calling this method from (see g_main_context_push_thread_default()).
             * You can then call gclue_location_proxy_new_finish() to get the result of the operation.
             *
             * See gclue_location_proxy_new_sync() for the synchronous, blocking version of this constructor.
             * @param connection A #GDBusConnection.
             * @param flags Flags from the #GDBusProxyFlags enumeration.
             * @param name A bus name (well-known or unique) or %NULL if @connection is not a message bus connection.
             * @param object_path An object path.
             * @param cancellable A #GCancellable or %NULL.
             * @param callback A #GAsyncReadyCallback to call when the request is satisfied.
             */
            "new"(connection: Gio.DBusConnection, flags: Gio.DBusProxyFlags, name: string | null, object_path: string, cancellable: Gio.Cancellable | null, callback: Gio.AsyncReadyCallback | null): void
            /**
             * Like gclue_location_proxy_new() but takes a #GBusType instead of a #GDBusConnection.
             *
             * When the operation is finished, @callback will be invoked in the thread-default main loop of the thread you are calling this method from (see g_main_context_push_thread_default()).
             * You can then call gclue_location_proxy_new_for_bus_finish() to get the result of the operation.
             *
             * See gclue_location_proxy_new_for_bus_sync() for the synchronous, blocking version of this constructor.
             * @param bus_type A #GBusType.
             * @param flags Flags from the #GDBusProxyFlags enumeration.
             * @param name A bus name (well-known or unique).
             * @param object_path An object path.
             * @param cancellable A #GCancellable or %NULL.
             * @param callback A #GAsyncReadyCallback to call when the request is satisfied.
             */
            new_for_bus(bus_type: Gio.BusType, flags: Gio.DBusProxyFlags, name: string, object_path: string, cancellable: Gio.Cancellable | null, callback: Gio.AsyncReadyCallback | null): void
        }

        const LocationProxy: LocationProxyClass
        

        namespace LocationSkeleton {
            interface SignalSignatures extends Gio.DBusInterfaceSkeleton.SignalSignatures, Location.SignalSignatures, Gio.DBusInterface.SignalSignatures {
            }

            interface ReadableProperties extends Gio.DBusInterfaceSkeleton.ReadableProperties, Location.ReadableProperties, Gio.DBusInterface.ReadableProperties {
            }

            interface WritableProperties extends Gio.DBusInterfaceSkeleton.WritableProperties, Location.WritableProperties, Gio.DBusInterface.WritableProperties {
            }

            interface ConstructOnlyProperties extends Gio.DBusInterfaceSkeleton.ConstructOnlyProperties, Location.ConstructOnlyProperties, Gio.DBusInterface.ConstructOnlyProperties {
            }
        }

        /**
         * The #GClueLocationSkeleton structure contains only private data and should only be accessed using the provided API.
         */
        interface LocationSkeleton extends Gio.DBusInterfaceSkeleton, Location, Gio.DBusInterface {
            readonly $signals: LocationSkeleton.SignalSignatures
            readonly $readableProperties: LocationSkeleton.ReadableProperties
            readonly $writableProperties: LocationSkeleton.WritableProperties
            readonly $constructOnlyProperties: LocationSkeleton.ConstructOnlyProperties
        }

        interface LocationSkeletonClass extends Omit<Gio.DBusInterfaceSkeletonClass, "new"> {
            readonly $gtype: GObject.GType<LocationSkeleton>
            readonly prototype: LocationSkeleton
            new (props?: Partial<GObject.ConstructorProps<LocationSkeleton>>): LocationSkeleton
            /**
             * .
             * @returns The skeleton object.
             */
            "new"(): LocationSkeleton
        }

        const LocationSkeleton: LocationSkeletonClass
        

        namespace ManagerProxy {
            interface SignalSignatures extends Gio.DBusProxy.SignalSignatures, Manager.SignalSignatures, Gio.AsyncInitable.SignalSignatures, Gio.DBusInterface.SignalSignatures, Gio.Initable.SignalSignatures {
            }

            interface ReadableProperties extends Gio.DBusProxy.ReadableProperties, Manager.ReadableProperties, Gio.AsyncInitable.ReadableProperties, Gio.DBusInterface.ReadableProperties, Gio.Initable.ReadableProperties {
            }

            interface WritableProperties extends Gio.DBusProxy.WritableProperties, Manager.WritableProperties, Gio.AsyncInitable.WritableProperties, Gio.DBusInterface.WritableProperties, Gio.Initable.WritableProperties {
            }

            interface ConstructOnlyProperties extends Gio.DBusProxy.ConstructOnlyProperties, Manager.ConstructOnlyProperties, Gio.AsyncInitable.ConstructOnlyProperties, Gio.DBusInterface.ConstructOnlyProperties, Gio.Initable.ConstructOnlyProperties {
            }
        }

        /**
         * The #GClueManagerProxy structure contains only private data and should only be accessed using the provided API.
         */
        interface ManagerProxy extends Gio.DBusProxy, Manager, Gio.AsyncInitable, Gio.DBusInterface, Gio.Initable {
            readonly $signals: ManagerProxy.SignalSignatures
            readonly $readableProperties: ManagerProxy.ReadableProperties
            readonly $writableProperties: ManagerProxy.WritableProperties
            readonly $constructOnlyProperties: ManagerProxy.ConstructOnlyProperties
        }

        interface ManagerProxyClass extends Omit<Gio.DBusProxyClass, "new"> {
            readonly $gtype: GObject.GType<ManagerProxy>
            readonly prototype: ManagerProxy
            new (props?: Partial<GObject.ConstructorProps<ManagerProxy>>): ManagerProxy
            /**
             * Finishes an operation started with gclue_manager_proxy_new().
             * @throws {GLib.Error}
             * @param res The #GAsyncResult obtained from the #GAsyncReadyCallback passed to gclue_manager_proxy_new().
             * @returns The constructed proxy object or %NULL if `error` is set.
             */
            new_finish(res: Gio.AsyncResult): ManagerProxy
            /**
             * Finishes an operation started with gclue_manager_proxy_new_for_bus().
             * @throws {GLib.Error}
             * @param res The #GAsyncResult obtained from the #GAsyncReadyCallback passed to gclue_manager_proxy_new_for_bus().
             * @returns The constructed proxy object or %NULL if `error` is set.
             */
            new_for_bus_finish(res: Gio.AsyncResult): ManagerProxy
            /**
             * Like gclue_manager_proxy_new_sync() but takes a #GBusType instead of a #GDBusConnection.
             *
             * The calling thread is blocked until a reply is received.
             *
             * See gclue_manager_proxy_new_for_bus() for the asynchronous version of this constructor.
             * @throws {GLib.Error}
             * @param bus_type A #GBusType.
             * @param flags Flags from the #GDBusProxyFlags enumeration.
             * @param name A bus name (well-known or unique).
             * @param object_path An object path.
             * @param cancellable A #GCancellable or %NULL.
             * @returns The constructed proxy object or %NULL if `error` is set.
             */
            new_for_bus_sync(bus_type: Gio.BusType, flags: Gio.DBusProxyFlags, name: string, object_path: string, cancellable: Gio.Cancellable | null): ManagerProxy
            /**
             * . See g_dbus_proxy_new_sync() for more details.
             *
             * The calling thread is blocked until a reply is received.
             *
             * See gclue_manager_proxy_new() for the asynchronous version of this constructor.
             * @throws {GLib.Error}
             * @param connection A #GDBusConnection.
             * @param flags Flags from the #GDBusProxyFlags enumeration.
             * @param name A bus name (well-known or unique) or %NULL if @connection is not a message bus connection.
             * @param object_path An object path.
             * @param cancellable A #GCancellable or %NULL.
             * @returns The constructed proxy object or %NULL if `error` is set.
             */
            new_sync(connection: Gio.DBusConnection, flags: Gio.DBusProxyFlags, name: string | null, object_path: string, cancellable: Gio.Cancellable | null): ManagerProxy
            /**
             * . See g_dbus_proxy_new() for more details.
             *
             * When the operation is finished, @callback will be invoked in the thread-default main loop of the thread you are calling this method from (see g_main_context_push_thread_default()).
             * You can then call gclue_manager_proxy_new_finish() to get the result of the operation.
             *
             * See gclue_manager_proxy_new_sync() for the synchronous, blocking version of this constructor.
             * @param connection A #GDBusConnection.
             * @param flags Flags from the #GDBusProxyFlags enumeration.
             * @param name A bus name (well-known or unique) or %NULL if @connection is not a message bus connection.
             * @param object_path An object path.
             * @param cancellable A #GCancellable or %NULL.
             * @param callback A #GAsyncReadyCallback to call when the request is satisfied.
             */
            "new"(connection: Gio.DBusConnection, flags: Gio.DBusProxyFlags, name: string | null, object_path: string, cancellable: Gio.Cancellable | null, callback: Gio.AsyncReadyCallback | null): void
            /**
             * Like gclue_manager_proxy_new() but takes a #GBusType instead of a #GDBusConnection.
             *
             * When the operation is finished, @callback will be invoked in the thread-default main loop of the thread you are calling this method from (see g_main_context_push_thread_default()).
             * You can then call gclue_manager_proxy_new_for_bus_finish() to get the result of the operation.
             *
             * See gclue_manager_proxy_new_for_bus_sync() for the synchronous, blocking version of this constructor.
             * @param bus_type A #GBusType.
             * @param flags Flags from the #GDBusProxyFlags enumeration.
             * @param name A bus name (well-known or unique).
             * @param object_path An object path.
             * @param cancellable A #GCancellable or %NULL.
             * @param callback A #GAsyncReadyCallback to call when the request is satisfied.
             */
            new_for_bus(bus_type: Gio.BusType, flags: Gio.DBusProxyFlags, name: string, object_path: string, cancellable: Gio.Cancellable | null, callback: Gio.AsyncReadyCallback | null): void
        }

        const ManagerProxy: ManagerProxyClass
        

        namespace ManagerSkeleton {
            interface SignalSignatures extends Gio.DBusInterfaceSkeleton.SignalSignatures, Manager.SignalSignatures, Gio.DBusInterface.SignalSignatures {
            }

            interface ReadableProperties extends Gio.DBusInterfaceSkeleton.ReadableProperties, Manager.ReadableProperties, Gio.DBusInterface.ReadableProperties {
            }

            interface WritableProperties extends Gio.DBusInterfaceSkeleton.WritableProperties, Manager.WritableProperties, Gio.DBusInterface.WritableProperties {
            }

            interface ConstructOnlyProperties extends Gio.DBusInterfaceSkeleton.ConstructOnlyProperties, Manager.ConstructOnlyProperties, Gio.DBusInterface.ConstructOnlyProperties {
            }
        }

        /**
         * The #GClueManagerSkeleton structure contains only private data and should only be accessed using the provided API.
         */
        interface ManagerSkeleton extends Gio.DBusInterfaceSkeleton, Manager, Gio.DBusInterface {
            readonly $signals: ManagerSkeleton.SignalSignatures
            readonly $readableProperties: ManagerSkeleton.ReadableProperties
            readonly $writableProperties: ManagerSkeleton.WritableProperties
            readonly $constructOnlyProperties: ManagerSkeleton.ConstructOnlyProperties
        }

        interface ManagerSkeletonClass extends Omit<Gio.DBusInterfaceSkeletonClass, "new"> {
            readonly $gtype: GObject.GType<ManagerSkeleton>
            readonly prototype: ManagerSkeleton
            new (props?: Partial<GObject.ConstructorProps<ManagerSkeleton>>): ManagerSkeleton
            /**
             * .
             * @returns The skeleton object.
             */
            "new"(): ManagerSkeleton
        }

        const ManagerSkeleton: ManagerSkeletonClass
        

        namespace Simple {
            interface SignalSignatures extends GObject.Object.SignalSignatures, Gio.AsyncInitable.SignalSignatures {
            }

            interface ReadableProperties extends GObject.Object.ReadableProperties, Gio.AsyncInitable.ReadableProperties {
                "client": ClientProxy | null
                "distance-threshold": number
                "location": LocationProxy | null
                "time-threshold": number
            }

            interface WritableProperties extends GObject.Object.WritableProperties, Gio.AsyncInitable.WritableProperties {
                "accuracy-level": AccuracyLevel
                "client": ClientProxy | null
                "desktop-id": string
                "distance-threshold": number
                "location": LocationProxy | null
                "time-threshold": number
            }

            interface ConstructOnlyProperties extends GObject.Object.ConstructOnlyProperties, Gio.AsyncInitable.ConstructOnlyProperties {
            }
        }

        /**
         */
        interface Simple extends GObject.Object, Gio.AsyncInitable {
            readonly $signals: Simple.SignalSignatures
            readonly $readableProperties: Simple.ReadableProperties
            readonly $writableProperties: Simple.WritableProperties
            readonly $constructOnlyProperties: Simple.ConstructOnlyProperties
            /**
             * The requested maximum accuracy level.
             * @default GCLUE_ACCURACY_LEVEL_NONE
             */
            set accuracyLevel(value: AccuracyLevel)
            /**
             * The client proxy. This is %NULL if @simple is not using a client proxy
             * (i-e when inside the Flatpak sandbox).
             */
            get client(): ClientProxy | null
            set client(value: ClientProxy | null)
            /**
             * The Desktop ID of the application.
             * @default NULL
             */
            set desktopId(value: string)
            /**
             * The current distance threshold in meters. This value is used by the
             * service when it gets new location info. If the distance moved is
             * below the threshold, it won't emit the LocationUpdated signal.
             *
             * When set to 0 (default), it always emits the signal.
             * @default 0
             */
            get distanceThreshold(): number
            set distanceThreshold(value: number)
            /**
             * The current location.
             */
            get location(): LocationProxy | null
            set location(value: LocationProxy | null)
            /**
             * The current time threshold in seconds. This value is used by the
             * service when it gets new location info. If the time passed is
             * below the threshold, it won't emit the LocationUpdated signal.
             *
             * When set to 0 (default), it always emits the signal.
             * @default 0
             */
            get timeThreshold(): number
            set timeThreshold(value: number)
            /**
             * Gets the client proxy, or %NULL if @simple is not using a client proxy (i-e
             * when inside the Flatpak sandbox).
             * @returns The client object.
             */
            get_client(): ClientProxy | null
            /**
             * Gets the current location.
             * @returns The last known location as #GClueLocation.
             */
            get_location(): Location | null
        }

        interface SimpleClass extends Omit<GObject.ObjectClass, "new"> {
            readonly $gtype: GObject.GType<Simple>
            readonly prototype: Simple
            new (props?: Partial<GObject.ConstructorProps<Simple>>): Simple
            /**
             * Finishes an operation started with #gclue_simple_new().
             * @throws {GLib.Error}
             * @param result The #GAsyncResult obtained from the #GAsyncReadyCallback passed to
                     #gclue_simple_new().
             * @returns The constructed proxy object or %NULL if `error` is set.
             */
            new_finish(result: Gio.AsyncResult): Simple
            /**
             * The synchronous and blocking version of #gclue_simple_new().
             * @throws {GLib.Error}
             * @param desktop_id The desktop file id (the basename of the desktop file).
             * @param accuracy_level The requested accuracy level as #GClueAccuracyLevel.
             * @param cancellable A #GCancellable or %NULL.
             * @returns The new #GClueSimple object or %NULL if `error` is set.
             */
            new_sync(desktop_id: string, accuracy_level: AccuracyLevel, cancellable: Gio.Cancellable | null): Simple
            /**
             * Finishes an operation started with #gclue_simple_new_with_thresholds().
             * @throws {GLib.Error}
             * @param result The #GAsyncResult obtained from the #GAsyncReadyCallback passed to
                     #gclue_simple_new_with_thresholds().
             * @returns The constructed proxy object or %NULL if `error` is set.
             */
            new_with_thresholds_finish(result: Gio.AsyncResult): Simple
            /**
             * The synchronous and blocking version of #gclue_simple_new_with_thresholds().
             * @throws {GLib.Error}
             * @param desktop_id The desktop file id (the basename of the desktop file).
             * @param accuracy_level The requested accuracy level as #GClueAccuracyLevel.
             * @param time_threshold Time threshold in seconds, 0 for no limit.
             * @param distance_threshold Distance threshold in meters, 0 for no limit.
             * @param cancellable A #GCancellable or %NULL.
             * @returns The new #GClueSimple object or %NULL if `error` is set.
             */
            new_with_thresholds_sync(desktop_id: string, accuracy_level: AccuracyLevel, time_threshold: number, distance_threshold: number, cancellable: Gio.Cancellable | null): Simple
            /**
             * Asynchronously creates a #GClueSimple instance. Use
             * #gclue_simple_new_finish() to get the created #GClueSimple instance.
             *
             * See #gclue_simple_new_sync() for the synchronous, blocking version
             * of this function.
             * @param desktop_id The desktop file id (the basename of the desktop file).
             * @param accuracy_level The requested accuracy level as #GClueAccuracyLevel.
             * @param cancellable A #GCancellable or %NULL.
             * @param callback A #GAsyncReadyCallback to call when the results are ready.
             */
            "new"(desktop_id: string, accuracy_level: AccuracyLevel, cancellable: Gio.Cancellable | null, callback: Gio.AsyncReadyCallback | null): void
            /**
             * Asynchronously creates a #GClueSimple instance. Use
             * #gclue_simple_new_with_thresholds_finish() to get the created #GClueSimple instance.
             *
             * See #gclue_simple_new_with_thresholds_sync() for the synchronous,
             * blocking version of this function.
             * @param desktop_id The desktop file id (the basename of the desktop file).
             * @param accuracy_level The requested accuracy level as #GClueAccuracyLevel.
             * @param time_threshold Time threshold in seconds, 0 for no limit.
             * @param distance_threshold Distance threshold in meters, 0 for no limit.
             * @param cancellable A #GCancellable or %NULL.
             * @param callback A #GAsyncReadyCallback to call when the results are ready.
             */
            new_with_thresholds(desktop_id: string, accuracy_level: AccuracyLevel, time_threshold: number, distance_threshold: number, cancellable: Gio.Cancellable | null, callback: Gio.AsyncReadyCallback | null): void
        }

        const Simple: SimpleClass
        none
        none
        /**
         */
        abstract class ClientProxyPrivate {
            static readonly $gtype: GObject.GType<ClientProxyPrivate>

            
        }
        none
        /**
         */
        abstract class ClientSkeletonPrivate {
            static readonly $gtype: GObject.GType<ClientSkeletonPrivate>

            
        }
        none
        none
        /**
         */
        abstract class LocationProxyPrivate {
            static readonly $gtype: GObject.GType<LocationProxyPrivate>

            
        }
        none
        /**
         */
        abstract class LocationSkeletonPrivate {
            static readonly $gtype: GObject.GType<LocationSkeletonPrivate>

            
        }
        none
        none
        /**
         */
        abstract class ManagerProxyPrivate {
            static readonly $gtype: GObject.GType<ManagerProxyPrivate>

            
        }
        none
        /**
         */
        abstract class ManagerSkeletonPrivate {
            static readonly $gtype: GObject.GType<ManagerSkeletonPrivate>

            
        }
        none
        /**
         */
        abstract class SimplePrivate {
            static readonly $gtype: GObject.GType<SimplePrivate>

            
        }
        /**
         *  D-Bus interface.
         * @returns A #GDBusInterfaceInfo. Do not free.
         */
        function client_interface_info(): Gio.DBusInterfaceInfo
        /**
         * Overrides all #GObject properties in the #GClueClient interface for a concrete class.
         * The properties are overridden in the order they are defined.
         * @param klass The class structure for a #GObject derived class.
         * @param property_id_begin The property id to assign to the first overridden property.
         * @returns The last property id.
         */
        function client_override_properties(klass: GObject.ObjectClass, property_id_begin: number): number
        /**
         *  D-Bus interface.
         * @returns A #GDBusInterfaceInfo. Do not free.
         */
        function location_interface_info(): Gio.DBusInterfaceInfo
        /**
         * Overrides all #GObject properties in the #GClueLocation interface for a concrete class.
         * The properties are overridden in the order they are defined.
         * @param klass The class structure for a #GObject derived class.
         * @param property_id_begin The property id to assign to the first overridden property.
         * @returns The last property id.
         */
        function location_override_properties(klass: GObject.ObjectClass, property_id_begin: number): number
        /**
         *  D-Bus interface.
         * @returns A #GDBusInterfaceInfo. Do not free.
         */
        function manager_interface_info(): Gio.DBusInterfaceInfo
        /**
         * Overrides all #GObject properties in the #GClueManager interface for a concrete class.
         * The properties are overridden in the order they are defined.
         * @param klass The class structure for a #GObject derived class.
         * @param property_id_begin The property id to assign to the first overridden property.
         * @returns The last property id.
         */
        function manager_override_properties(klass: GObject.ObjectClass, property_id_begin: number): number
        
        namespace AccuracyLevel {
            const $gtype: GObject.GType<AccuracyLevel>
        }

        /**
         */
        enum AccuracyLevel {
            /**
             */
            "NONE" = 0,
            /**
             */
            "COUNTRY" = 1,
            /**
             */
            "CITY" = 4,
            /**
             */
            "NEIGHBORHOOD" = 5,
            /**
             */
            "STREET" = 6,
            /**
             */
            "EXACT" = 8,
        }
        
        namespace ClientProxyCreateFlags {
            const $gtype: GObject.GType<ClientProxyCreateFlags>
        }

        /**
         */
        enum ClientProxyCreateFlags {
            /**
             */
            "NONE" = 0,
            /**
             */
            "AUTO_DELETE" = 1,
        }
    }

    export default Geoclue
}