
/// <reference path="./GLib-2.0.d.ts" />
/// <reference path="./GModule-2.0.d.ts" />
/// <reference path="./GObject-2.0.d.ts" />
/// <reference path="./Gio-2.0.d.ts" />
/// <reference path="./freetype2-2.0.d.ts" />
/// <reference path="./HarfBuzz-0.0.d.ts" />
/// <reference path="./cairo-1.0.d.ts" />
/// <reference path="./Pango-1.0.d.ts" />
/// <reference path="./GdkPixbuf-2.0.d.ts" />
/// <reference path="./PangoCairo-1.0.d.ts" />
/// <reference path="./Gdk-4.0.d.ts" />
/// <reference path="./Gly-2.d.ts" />

/**
 * Type Definitions for GJS (https://gjs.guide/), generated by [GirGen](https://github.com/aylur/girgen)
 * If you found a bug, create a bug report on [GirGen's Repository](https://github.com/aylur/girgen/issues/new)
 */
declare module "gi://GlyGtk4?version=2" {
    import type GLib from "gi://GLib?version=2.0"
    import type GModule from "gi://GModule?version=2.0"
    import type GObject from "gi://GObject?version=2.0"
    import type Gio from "gi://Gio?version=2.0"
    import type freetype2 from "gi://freetype2?version=2.0"
    import type HarfBuzz from "gi://HarfBuzz?version=0.0"
    import type cairo from "gi://cairo?version=1.0"
    import type Pango from "gi://Pango?version=1.0"
    import type GdkPixbuf from "gi://GdkPixbuf?version=2.0"
    import type PangoCairo from "gi://PangoCairo?version=1.0"
    import type Gdk from "gi://Gdk?version=4.0"
    import type Gly from "gi://Gly?version=2"

    


    namespace GlyGtk4 {
        const __name__: "GlyGtk4"
        const __version: "2"
        /**
         * Gets the actual image from a frame. See the [class@Gly.Loader] docs
         * for a complete example.
         * @since 2.0
         * @param frame Frame
         * @returns A GDK Texture
         */
        function frame_get_texture(frame: Gly.Frame): Gdk.Texture
    }

    export default GlyGtk4
}