
/// <reference path="./GLib-2.0.d.ts" />
/// <reference path="./GModule-2.0.d.ts" />
/// <reference path="./GObject-2.0.d.ts" />
/// <reference path="./Gst-1.0.d.ts" />
/// <reference path="./GstBase-1.0.d.ts" />
/// <reference path="./GstAudio-1.0.d.ts" />
/// <reference path="./GstVideo-1.0.d.ts" />
/// <reference path="./GstPbutils-1.0.d.ts" />

/**
 * Type Definitions for GJS (https://gjs.guide/), generated by [GirGen](https://github.com/aylur/girgen)
 * If you found a bug, create a bug report on [GirGen's Repository](https://github.com/aylur/girgen/issues/new)
 */
declare module "gi://GstTranscoder?version=1.0" {
    import type GLib from "gi://GLib?version=2.0"
    import type GModule from "gi://GModule?version=2.0"
    import type GObject from "gi://GObject?version=2.0"
    import type Gst from "gi://Gst?version=1.0"
    import type GstBase from "gi://GstBase?version=1.0"
    import type GstAudio from "gi://GstAudio?version=1.0"
    import type GstVideo from "gi://GstVideo?version=1.0"
    import type GstPbutils from "gi://GstPbutils?version=1.0"

    


    namespace GstTranscoder {
        const __name__: "GstTranscoder"
        const __version: "1.0"
        

        namespace Transcoder {
            interface SignalSignatures extends Gst.Object.SignalSignatures {
            }

            interface ReadableProperties extends Gst.Object.ReadableProperties {
                "avoid-reencoding": boolean
                "dest-uri": string
                "duration": number
                "pipeline": Gst.Element
                "position": number
                "position-update-interval": number
                "profile": GstPbutils.EncodingProfile
                "src-uri": string
            }

            interface WritableProperties extends Gst.Object.WritableProperties {
                "avoid-reencoding": boolean
                "dest-uri": string
                "duration": number
                "pipeline": Gst.Element
                "position": number
                "position-update-interval": number
                "profile": GstPbutils.EncodingProfile
                "src-uri": string
            }

            interface ConstructOnlyProperties extends Gst.Object.ConstructOnlyProperties {
            }
        }

        /**
         */
        interface Transcoder extends Gst.Object {
            readonly $signals: Transcoder.SignalSignatures
            readonly $readableProperties: Transcoder.ReadableProperties
            readonly $writableProperties: Transcoder.WritableProperties
            readonly $constructOnlyProperties: Transcoder.ConstructOnlyProperties
            /**
             * See #encodebin:avoid-reencoding
             * @default FALSE
             */
            get avoidReencoding(): boolean
            set avoidReencoding(value: boolean)
            /**
             * @default NULL
             */
            get destUri(): string
            set destUri(value: string)
            /**
             * @default 18446744073709551615
             */
            get duration(): number
            set duration(value: number)
            /**
             */
            get pipeline(): Gst.Element
            set pipeline(value: Gst.Element)
            /**
             * @default 18446744073709551615
             */
            get position(): number
            set position(value: number)
            /**
             * @default 100
             */
            get positionUpdateInterval(): number
            set positionUpdateInterval(value: number)
            /**
             */
            get profile(): GstPbutils.EncodingProfile
            set profile(value: GstPbutils.EncodingProfile)
            /**
             * @default NULL
             */
            get srcUri(): string
            set srcUri(value: string)
            /**
             * @returns %TRUE if the transcoder tries to avoid reencoding streams where reencoding is not strictly needed, %FALSE otherwise.
             */
            get_avoid_reencoding(): boolean
            /**
             * Gets the URI of the destination of the transcoded stream.
             * @returns a string containing the URI of the destination of the transcoded stream. g_free() after usage.
             */
            get_dest_uri(): string
            /**
             * Retrieves the duration of the media stream that self represents.
             * @returns the duration of the transcoding media stream, in nanoseconds.
             */
            get_duration(): Gst.ClockTime
            /**
             * GstTranscoder API exposes a #GstBus instance which purpose is to provide data
             * structures representing transcoder-internal events in form of #GstMessage-s of
             * type GST_MESSAGE_APPLICATION.
             *
             * Each message carries a "transcoder-message" field of type #GstTranscoderMessage.
             * Further fields of the message data are specific to each possible value of
             * that enumeration.
             *
             * Applications can consume the messages asynchronously within their own
             * event-loop / UI-thread etc. Note that in case the application does not
             * consume the messages, the bus will accumulate these internally and eventually
             * fill memory. To avoid that, the bus has to be set "flushing".
             * @since 1.20
             * @returns The transcoder message bus instance
             */
            get_message_bus(): Gst.Bus
            /**
             * @returns The internal uritranscodebin instance
             */
            get_pipeline(): Gst.Element
            /**
             * @returns the absolute position time, in nanoseconds, of the transcoding stream.
             */
            get_position(): Gst.ClockTime
            /**
             * @returns current position update interval in milliseconds
             */
            get_position_update_interval(): number
            /**
             * Gets the #GstTranscoderSignalAdapter attached to @self if it is attached to
             * the right #GMainContext. If no #GstTranscoderSignalAdapter has been created
             * yet, it will be created and returned, other calls will return that same
             * adapter until it is destroyed, at which point, a new one can be attached the
             * same way.
             * @since 1.20
             * @param context A #GMainContext on which the main-loop will process
                                  transcoder bus messages on. Can be NULL (thread-default
                                  context will be used then).
             * @returns The #GstTranscoderSignalAdapter to connect signal handlers to.
             */
            get_signal_adapter(context: GLib.MainContext | null): TranscoderSignalAdapter | null
            /**
             * Gets the URI of the currently-transcoding stream.
             * @returns a string containing the URI of the source stream. g_free() after usage.
             */
            get_source_uri(): string
            /**
             * Gets the #GstTranscoderSignalAdapter attached to @self to emit signals from
             * its thread of emission.
             * @since 1.20
             * @returns The #GstTranscoderSignalAdapter to connect signal handlers to.
             */
            get_sync_signal_adapter(): TranscoderSignalAdapter
            /**
             * Run the transcoder task synchonously. You can connect
             * to the 'position' signal to get information about the
             * progress of the transcoding.
             * @throws {GLib.Error}
             */
            run(): boolean
            /**
             * Run the transcoder task asynchronously. You should connect
             * to the 'done' signal to be notified about when the
             * transcoding is done, and to the 'error' signal to be
             * notified about any error.
             */
            run_async(): void
            /**
             * @param avoid_reencoding %TRUE if the transcoder should try to avoid reencoding
            streams where * reencoding is not strictly needed, %FALSE otherwise.
             */
            set_avoid_reencoding(avoid_reencoding: boolean): void
            /**
             * Sets @cpu_usage as target percentage CPU usage of the process running the
             * transcoding task. It will modulate the transcoding speed to reach that target
             * usage.
             * @param cpu_usage The percentage of the CPU the process running the transcoder
            should try to use. It takes into account the number of cores available.
             */
            set_cpu_usage(cpu_usage: number): void
            /**
             * Set interval in milliseconds between two position-updated signals.
             * Pass 0 to stop updating the position.
             * @param interval interval in ms
             */
            set_position_update_interval(interval: number): void
        }

        interface TranscoderClass extends Omit<Gst.ObjectClass, "new"> {
            readonly $gtype: GObject.GType<Transcoder>
            readonly prototype: Transcoder
            new (props?: Partial<GObject.ConstructorProps<Transcoder>>): Transcoder
            /**
             * @param source_uri The URI of the media stream to transcode
             * @param dest_uri The URI of the destination of the transcoded stream
             * @param encoding_profile The serialized #GstEncodingProfile defining the output
            format. Have a look at the #GstEncodingProfile documentation to find more
            about the serialization format.
             * @returns a new #GstTranscoder instance
             */
            "new"(source_uri: string, dest_uri: string, encoding_profile: string): Transcoder
            /**
             * @param source_uri The URI of the media stream to transcode
             * @param dest_uri The URI of the destination of the transcoded stream
             * @param profile The #GstEncodingProfile defining the output format
            have a look at the #GstEncodingProfile documentation to find more
            about the serialization format.
             * @returns a new #GstTranscoder instance
             */
            new_full(source_uri: string, dest_uri: string, profile: GstPbutils.EncodingProfile): Transcoder
            /**
             * @since 1.20
             * @param msg A #GstMessage
             * @returns A #gboolean indicating whether the passes message represents a #GstTranscoder message or not.
             */
            is_transcoder_message(msg: Gst.Message): boolean
        }

        const Transcoder: TranscoderClass
        

        namespace TranscoderSignalAdapter {
            interface SignalSignatures extends GObject.Object.SignalSignatures {
                /**
                 */
                "done"(): void
                /**
                 * @param object
                 */
                "duration-changed"(object: number): void
                /**
                 * @param object
                 * @param p0
                 */
                "error"(object: GLib.Error, p0: Gst.Structure): void
                /**
                 * @param object
                 */
                "position-updated"(object: number): void
                /**
                 * @param object
                 */
                "state-changed"(object: TranscoderState): void
                /**
                 * @param object
                 * @param p0
                 */
                "warning"(object: GLib.Error, p0: Gst.Structure): void
            }

            interface ReadableProperties extends GObject.Object.ReadableProperties {
                "transcoder": Transcoder | null
            }

            interface WritableProperties extends GObject.Object.WritableProperties {
                "transcoder": Transcoder | null
            }

            interface ConstructOnlyProperties extends GObject.Object.ConstructOnlyProperties {
            }
        }

        /**
         * Transforms #GstTranscoder bus messages to signals from the adapter object.
         * @since 1.20
         */
        interface TranscoderSignalAdapter extends GObject.Object {
            readonly $signals: TranscoderSignalAdapter.SignalSignatures
            readonly $readableProperties: TranscoderSignalAdapter.ReadableProperties
            readonly $writableProperties: TranscoderSignalAdapter.WritableProperties
            readonly $constructOnlyProperties: TranscoderSignalAdapter.ConstructOnlyProperties
            /**
             * The #GstTranscoder tracked by the adapter.
             * @since 1.20
             */
            get transcoder(): Transcoder | null
            set transcoder(value: Transcoder | null)
            /**
             * @since 1.20
             * @returns The #GstTranscoder `self` is tracking
             */
            get_transcoder(): Transcoder | null
        }

        interface TranscoderSignalAdapterClass extends Omit<GObject.ObjectClass, "new"> {
            readonly $gtype: GObject.GType<TranscoderSignalAdapter>
            readonly prototype: TranscoderSignalAdapter
            new (props?: Partial<GObject.ConstructorProps<TranscoderSignalAdapter>>): TranscoderSignalAdapter
        }

        const TranscoderSignalAdapter: TranscoderSignalAdapterClass
        none
        none
        /**
         * Gets a string representing the given error.
         * @param error a #GstTranscoderError
         * @returns a string with the given error.
         */
        function transcoder_error_get_name(error: TranscoderError): string
        /**
         */
        function transcoder_error_quark(): GLib.Quark
        /**
         * Returns (transfer none): The message name
         * @since 1.20
         * @param message a #GstTranscoderMessage
         */
        function transcoder_message_get_name(message: TranscoderMessage): string
        /**
         * Parse the given duration @msg and extract the corresponding #GstClockTime
         * @since 1.20
         * @param msg A #GstMessage
         * @returns , the resulting duration
         */
        function transcoder_message_parse_duration(msg: Gst.Message): Gst.ClockTime
        /**
         * Parse the given error @msg and extract the corresponding #GError
         * @since 1.20
         * @param msg A #GstMessage
         * @returns , the resulting error, (transfer full): A GstStructure containing extra details about the error
         */
        function transcoder_message_parse_error(msg: Gst.Message): Gst.Structure
        /**
         * Parse the given position @msg and extract the corresponding #GstClockTime
         * @since 1.20
         * @param msg A #GstMessage
         * @returns , the resulting position
         */
        function transcoder_message_parse_position(msg: Gst.Message): Gst.ClockTime
        /**
         * Parse the given state @msg and extract the corresponding #GstTranscoderState
         * @since 1.20
         * @param msg A #GstMessage
         * @returns , the resulting state
         */
        function transcoder_message_parse_state(msg: Gst.Message): TranscoderState
        /**
         * Parse the given error @msg and extract the corresponding #GError warning
         * @since 1.20
         * @param msg A #GstMessage
         * @returns , the resulting warning, (transfer full): A GstStructure containing extra details about the warning
         */
        function transcoder_message_parse_warning(msg: Gst.Message): Gst.Structure
        /**
         * Gets a string representing the given state.
         * @since 1.20
         * @param state a #GstTranscoderState
         * @returns a string with the name of the state.
         */
        function transcoder_state_get_name(state: TranscoderState): string
        
        abstract class TranscoderError extends GLib.Error {
            static readonly $gtype: GObject.GType<TranscoderError>
            /**
             * generic error.
             */
            static readonly "FAILED": 0
        }
        /**
         * Gets a string representing the given error.
         * @param error a #GstTranscoderError
         * @returns a string with the given error.
         */
        function get_name(error: TranscoderError): string
        /**
         */
        function quark(): GLib.Quark
        
        namespace TranscoderMessage {
            const $gtype: GObject.GType<TranscoderMessage>
        }

        /**
         * Types of messages that will be posted on the transcoder API bus.
         *
         * See also #gst_transcoder_get_message_bus()
         * @since 1.20
         */
        enum TranscoderMessage {
            /**
             * Sink position changed
             */
            "POSITION_UPDATED" = 0,
            /**
             * Duration of stream changed
             */
            "DURATION_CHANGED" = 1,
            /**
             * Pipeline state changed
             */
            "STATE_CHANGED" = 2,
            /**
             * Transcoding is done
             */
            "DONE" = 3,
            /**
             * Message contains an error
             */
            "ERROR" = 4,
            /**
             * Message contains an error
             */
            "WARNING" = 5,
        }
        /**
         * Returns (transfer none): The message name
         * @since 1.20
         * @param message a #GstTranscoderMessage
         */
        function get_name(message: TranscoderMessage): string
        /**
         * Parse the given duration @msg and extract the corresponding #GstClockTime
         * @since 1.20
         * @param msg A #GstMessage
         * @returns , the resulting duration
         */
        function parse_duration(msg: Gst.Message): Gst.ClockTime
        /**
         * Parse the given error @msg and extract the corresponding #GError
         * @since 1.20
         * @param msg A #GstMessage
         * @returns , the resulting error, (transfer full): A GstStructure containing extra details about the error
         */
        function parse_error(msg: Gst.Message): Gst.Structure
        /**
         * Parse the given position @msg and extract the corresponding #GstClockTime
         * @since 1.20
         * @param msg A #GstMessage
         * @returns , the resulting position
         */
        function parse_position(msg: Gst.Message): Gst.ClockTime
        /**
         * Parse the given state @msg and extract the corresponding #GstTranscoderState
         * @since 1.20
         * @param msg A #GstMessage
         * @returns , the resulting state
         */
        function parse_state(msg: Gst.Message): TranscoderState
        /**
         * Parse the given error @msg and extract the corresponding #GError warning
         * @since 1.20
         * @param msg A #GstMessage
         * @returns , the resulting warning, (transfer full): A GstStructure containing extra details about the warning
         */
        function parse_warning(msg: Gst.Message): Gst.Structure
        
        namespace TranscoderState {
            const $gtype: GObject.GType<TranscoderState>
        }

        /**
         * High level representation of the transcoder pipeline state.
         * @since 1.20
         */
        enum TranscoderState {
            /**
             * the transcoder is stopped.
             */
            "STOPPED" = 0,
            /**
             * the transcoder is paused.
             */
            "PAUSED" = 1,
            /**
             * the transcoder is currently transcoding a
             * stream.
             */
            "PLAYING" = 2,
        }
        /**
         * Gets a string representing the given state.
         * @since 1.20
         * @param state a #GstTranscoderState
         * @returns a string with the name of the state.
         */
        function get_name(state: TranscoderState): string
    }

    export default GstTranscoder
}