
/// <reference path="./GLib-2.0.d.ts" />
/// <reference path="./GModule-2.0.d.ts" />
/// <reference path="./GObject-2.0.d.ts" />
/// <reference path="./Gio-2.0.d.ts" />

/**
 * Type Definitions for GJS (https://gjs.guide/), generated by [GirGen](https://github.com/aylur/girgen)
 * If you found a bug, create a bug report on [GirGen's Repository](https://github.com/aylur/girgen/issues/new)
 */
declare module "gi://Libproxy?version=1.0" {
    import type GLib from "gi://GLib?version=2.0"
    import type GModule from "gi://GModule?version=2.0"
    import type GObject from "gi://GObject?version=2.0"
    import type Gio from "gi://Gio?version=2.0"

    


    namespace Libproxy {
        const __name__: "Libproxy"
        const __version: "1.0"
        /**
         */
        abstract class ProxyFactory {
            static readonly $gtype: GObject.GType<ProxyFactory>

            
            /**
             * Creates a new `pxProxyFactory` instance.
             *
             * This instance should be kept around as long as possible as it contains
             * cached data to increase performance.  Memory usage should be minimal
             * (cache is small) and the cache lifespan is handled automatically.
             * @returns The newly created `pxProxyFactory`
             */
            static "new"(): ProxyFactory
            /**
             * Frees the proxy array returned by @px_proxy_factory_get_proxies when no
             * longer used.
             *
             * @since 0.4.16
             * @param proxies a %NULL-terminated array of proxies
             */
            static free_proxies(proxies: string[]): void
            /**
             * Frees the `pxProxyFactory`.
             */
            free(): void
            /**
             * ://[username:password@]proxy:port
             *
             *   - direct://
             *
             * Please note that the username and password in the above URLs are optional
             * and should be use to authenticate the connection if present.
             *
             * For SOCKS proxies, when the protocol version is specified (socks4:// or
             * socks5://), it is expected that only this version is used. When only
             * socks:// is set, the client MUST try SOCKS version 5 protocol and, on
             * connection failure, fallback to SOCKS version 4.
             *
             * Other proxying protocols may exist. It is expected that the returned
             * configuration scheme shall match the network service name of the
             * proxy protocol or the service name of the protocol being proxied if the
             * previous does not exist. As an example, on Mac OS X you can configure a
             * RTSP streaming proxy. The expected returned configuration would be:
             *
             *   - rtsp://[username:password@]proxy:port
             *
             * To free the returned value, call @px_proxy_factory_free_proxies.
             * @param url Get proxxies for specificed URL
             * @returns a list of proxies
             */
            get_proxies(url: string): string[]
        }
        /**
         * Frees the proxy array returned by @px_proxy_factory_get_proxies when no
         * longer used.
         *
         * @since 0.4.16
         * @param proxies a %NULL-terminated array of proxies
         */
        function proxy_factory_free_proxies(proxies: string[]): void
    }

    export default Libproxy
}