
/// <reference path="./GObject-2.0.d.ts" />
/// <reference path="./GLib-2.0.d.ts" />

/**
 * Type Definitions for GJS (https://gjs.guide/), generated by [GirGen](https://github.com/aylur/girgen)
 * If you found a bug, create a bug report on [GirGen's Repository](https://github.com/aylur/girgen/issues/new)
 */
declare module "gi://libxml2?version=2.0" {
    import type GObject from "gi://GObject?version=2.0"
    import type GLib from "gi://GLib?version=2.0"

    


    namespace libxml2 {
        const __name__: "libxml2"
        const __version: "2.0"
        /**
         */
        abstract class Node {
            static readonly $gtype: GObject.GType<Node>

            
        }
        /**
         */
        abstract class NodePtr {
            static readonly $gtype: GObject.GType<NodePtr>

            
        }
        /**
         */
        abstract class Doc {
            static readonly $gtype: GObject.GType<Doc>

            
        }
        /**
         */
        abstract class DocPtr {
            static readonly $gtype: GObject.GType<DocPtr>

            
        }
        /**
         */
        abstract class NsPtr {
            static readonly $gtype: GObject.GType<NsPtr>

            
        }
        /**
         */
        abstract class Char {
            static readonly $gtype: GObject.GType<Char>

            
        }
        /**
         */
        abstract class TextWriter {
            static readonly $gtype: GObject.GType<TextWriter>

            
        }
        /**
         */
        abstract class TextReader {
            static readonly $gtype: GObject.GType<TextReader>

            
        }
        /**
         */
        function dummy(): void
    }

    export default libxml2
}