
/// <reference path="./GObject-2.0.d.ts" />
/// <reference path="./GLib-2.0.d.ts" />

/**
 * Type Definitions for GJS (https://gjs.guide/), generated by [GirGen](https://github.com/aylur/girgen)
 * If you found a bug, create a bug report on [GirGen's Repository](https://github.com/aylur/girgen/issues/new)
 */
declare module "gi://libxml2?version=2.0" {
    import type GObject from "gi://GObject?version=2.0"
    import type GLib from "gi://GLib?version=2.0"

    

    namespace libxml2 {
        

        interface NodeStruct {
            readonly $gtype: GObject.GType<Node>
            [Symbol.hasInstance](instance: unknown): instance is Node
        }

        interface Node {
        }

        interface $Exports {
            Node: NodeStruct
        }
        

        interface NodePtrStruct {
            readonly $gtype: GObject.GType<NodePtr>
            [Symbol.hasInstance](instance: unknown): instance is NodePtr
        }

        interface NodePtr {
        }

        interface $Exports {
            NodePtr: NodePtrStruct
        }
        

        interface DocStruct {
            readonly $gtype: GObject.GType<Doc>
            [Symbol.hasInstance](instance: unknown): instance is Doc
        }

        interface Doc {
        }

        interface $Exports {
            Doc: DocStruct
        }
        

        interface DocPtrStruct {
            readonly $gtype: GObject.GType<DocPtr>
            [Symbol.hasInstance](instance: unknown): instance is DocPtr
        }

        interface DocPtr {
        }

        interface $Exports {
            DocPtr: DocPtrStruct
        }
        

        interface NsPtrStruct {
            readonly $gtype: GObject.GType<NsPtr>
            [Symbol.hasInstance](instance: unknown): instance is NsPtr
        }

        interface NsPtr {
        }

        interface $Exports {
            NsPtr: NsPtrStruct
        }
        

        interface CharStruct {
            readonly $gtype: GObject.GType<Char>
            [Symbol.hasInstance](instance: unknown): instance is Char
        }

        interface Char {
        }

        interface $Exports {
            Char: CharStruct
        }
        

        interface TextWriterStruct {
            readonly $gtype: GObject.GType<TextWriter>
            [Symbol.hasInstance](instance: unknown): instance is TextWriter
        }

        interface TextWriter {
        }

        interface $Exports {
            TextWriter: TextWriterStruct
        }
        

        interface TextReaderStruct {
            readonly $gtype: GObject.GType<TextReader>
            [Symbol.hasInstance](instance: unknown): instance is TextReader
        }

        interface TextReader {
        }

        interface $Exports {
            TextReader: TextReaderStruct
        }

        interface $Exports {
            __name__: "libxml2"
            __version: "2.0"
            /**
             */
            dummy(): void
        }
    }

    const libxml2: libxml2.$Exports
    export default libxml2
}