
/// <reference path="./GObject-2.0.d.ts" />
/// <reference path="./GLib-2.0.d.ts" />

/**
 * Type Definitions for GJS (https://gjs.guide/), generated by [GirGen](https://github.com/aylur/girgen)
 * If you found a bug, create a bug report on [GirGen's Repository](https://github.com/aylur/girgen/issues/new)
 */
declare module "gi://win32?version=1.0" {
    import type GObject from "gi://GObject?version=2.0"
    import type GLib from "gi://GLib?version=2.0"

    


    namespace win32 {
        const __name__: "win32"
        const __version: "1.0"
        /**
         */
        abstract class MSG {
            static readonly $gtype: GObject.GType<MSG>

            
        }
        /**
         */
        type HWND = number
        /**
         */
        type HICON = number
        /**
         */
        type HCURSOR = number
        /**
         */
        type HGDIOBJ = number
    }

    export default win32
}