
/// <reference path="./GObject-2.0.d.ts" />
/// <reference path="./GLib-2.0.d.ts" />

/**
 * Type Definitions for GJS (https://gjs.guide/), generated by [GirGen](https://github.com/aylur/girgen)
 * If you found a bug, create a bug report on [GirGen's Repository](https://github.com/aylur/girgen/issues/new)
 */
declare module "gi://win32?version=1.0" {
    import type GObject from "gi://GObject?version=2.0"
    import type GLib from "gi://GLib?version=2.0"

    

    namespace win32 {
        

        interface MSGStruct {
            readonly $gtype: GObject.GType<MSG>
            [Symbol.hasInstance](instance: unknown): instance is MSG
        }

        interface MSG {
        }

        interface $Exports {
            MSG: MSGStruct
        }
        /**
         */
        type HWND = number
        /**
         */
        type HICON = number
        /**
         */
        type HCURSOR = number
        /**
         */
        type HGDIOBJ = number

        interface $Exports {
            __name__: "win32"
            __version: "1.0"
        }
    }

    const win32: win32.$Exports
    export default win32
}