
/// <reference path="./GLib-2.0.d.ts" />
/// <reference path="./GObject-2.0.d.ts" />
/// <reference path="./GModule-2.0.d.ts" />
/// <reference path="./Gio-2.0.d.ts" />
/// <reference path="./freetype2-2.0.d.ts" />
/// <reference path="./HarfBuzz-0.0.d.ts" />
/// <reference path="./cairo-1.0.d.ts" />
/// <reference path="./GdkPixbuf-2.0.d.ts" />
/// <reference path="./Pango-1.0.d.ts" />
/// <reference path="./Atk-1.0.d.ts" />
/// <reference path="./Gdk-3.0.d.ts" />
/// <reference path="./xlib-2.0.d.ts" />
/// <reference path="./Gtk-3.0.d.ts" />
/// <reference path="./Xdp-1.0.d.ts" />

/**
 * Type Definitions for GJS (https://gjs.guide/), generated by [GirGen](https://github.com/aylur/girgen)
 * If you found a bug, create a bug report on [GirGen's Repository](https://github.com/aylur/girgen/issues/new)
 */
declare module "gi://XdpGtk3?version=1.0" {
    import type GLib from "gi://GLib?version=2.0"
    import type GObject from "gi://GObject?version=2.0"
    import type GModule from "gi://GModule?version=2.0"
    import type Gio from "gi://Gio?version=2.0"
    import type freetype2 from "gi://freetype2?version=2.0"
    import type HarfBuzz from "gi://HarfBuzz?version=0.0"
    import type cairo from "gi://cairo?version=1.0"
    import type GdkPixbuf from "gi://GdkPixbuf?version=2.0"
    import type Pango from "gi://Pango?version=1.0"
    import type Atk from "gi://Atk?version=1.0"
    import type Gdk from "gi://Gdk?version=3.0"
    import type xlib from "gi://xlib?version=2.0"
    import type Gtk from "gi://Gtk?version=3.0"
    import type Xdp from "gi://Xdp?version=1.0"

    /**
     * Do **not** import this at runtime.
     * This namespace is only exported for module augmentation.
     */
    export namespace GI {
        

        namespace XdpGtk3 {

            interface $Exports {
                __name__: "XdpGtk3"
                __version__: "1.0"
                /**
                 * Creates a new {@link Parent} from `window`.
                 * @param window a {@link Gtk.Window}
                 * @returns a {@link Parent}
                 */
                parent_new_gtk(window: Gtk.Window): Xdp.Parent
            }
        }

        const XdpGtk3: XdpGtk3.$Exports
    }

    export default GI.XdpGtk3
}