
/// <reference path="./GObject-2.0.d.ts" />
/// <reference path="./GLib-2.0.d.ts" />

/**
 * Type Definitions for GJS (https://gjs.guide/), generated by [GirGen](https://github.com/aylur/girgen)
 * If you found a bug, create a bug report on [GirGen's Repository](https://github.com/aylur/girgen/issues/new)
 */
declare module "gi://xfixes?version=4.0" {
    import type GObject from "gi://GObject?version=2.0"
    import type GLib from "gi://GLib?version=2.0"

    


    namespace xfixes {
        const __name__: "xfixes"
        const __version: "4.0"
        /**
         */
        abstract class XserverRegion {
            static readonly $gtype: GObject.GType<XserverRegion>

            
        }
    }

    export default xfixes
}