
/// <reference path="./xlib-2.0.d.ts" />
/// <reference path="./GObject-2.0.d.ts" />
/// <reference path="./GLib-2.0.d.ts" />

/**
 * Type Definitions for GJS (https://gjs.guide/), generated by [GirGen](https://github.com/aylur/girgen)
 * If you found a bug, create a bug report on [GirGen's Repository](https://github.com/aylur/girgen/issues/new)
 */
declare module "gi://xft?version=2.0" {
    import type xlib from "gi://xlib?version=2.0"
    import type GObject from "gi://GObject?version=2.0"
    import type GLib from "gi://GLib?version=2.0"

    

    namespace xft {
        

        interface ColorStruct {
            readonly $gtype: GObject.GType<Color>
            [Symbol.hasInstance](instance: unknown): instance is Color
        }

        interface Color {
        }

        interface $Exports {
            Color: ColorStruct
        }
        

        interface DrawStruct {
            readonly $gtype: GObject.GType<Draw>
            [Symbol.hasInstance](instance: unknown): instance is Draw
        }

        interface Draw {
        }

        interface $Exports {
            Draw: DrawStruct
        }
        

        interface FontStruct {
            readonly $gtype: GObject.GType<Font>
            [Symbol.hasInstance](instance: unknown): instance is Font
        }

        interface Font {
        }

        interface $Exports {
            Font: FontStruct
        }
        

        interface GlyphSpecStruct {
            readonly $gtype: GObject.GType<GlyphSpec>
            [Symbol.hasInstance](instance: unknown): instance is GlyphSpec
        }

        interface GlyphSpec {
        }

        interface $Exports {
            GlyphSpec: GlyphSpecStruct
        }

        interface $Exports {
            __name__: "xft"
            __version: "2.0"
            /**
             */
            init(): void
        }
    }

    const xft: xft.$Exports
    export default xft
}