
/// <reference path="./GObject-2.0.d.ts" />
/// <reference path="./GLib-2.0.d.ts" />

/**
 * Type Definitions for GJS (https://gjs.guide/), generated by [GirGen](https://github.com/aylur/girgen)
 * If you found a bug, create a bug report on [GirGen's Repository](https://github.com/aylur/girgen/issues/new)
 */
declare module "gi://xrandr?version=1.3" {
    import type GObject from "gi://GObject?version=2.0"
    import type GLib from "gi://GLib?version=2.0"

    


    namespace xrandr {
        const __name__: "xrandr"
        const __version: "1.3"
        /**
         */
        abstract class ScreenSize {
            static readonly $gtype: GObject.GType<ScreenSize>

            
        }
        /**
         */
        abstract class ScreenChangeNotifyEvent {
            static readonly $gtype: GObject.GType<ScreenChangeNotifyEvent>

            
        }
        /**
         */
        abstract class NotifyEvent {
            static readonly $gtype: GObject.GType<NotifyEvent>

            
        }
        /**
         */
        abstract class ScreenResources {
            static readonly $gtype: GObject.GType<ScreenResources>

            
        }
        /**
         */
        abstract class OutputChangeNotifyEvent {
            static readonly $gtype: GObject.GType<OutputChangeNotifyEvent>

            
        }
        /**
         */
        abstract class CrtcChangeNotifyEvent {
            static readonly $gtype: GObject.GType<CrtcChangeNotifyEvent>

            
        }
        /**
         */
        abstract class OutputPropertyNotifyEvent {
            static readonly $gtype: GObject.GType<OutputPropertyNotifyEvent>

            
        }
    }

    export default xrandr
}